// THE MEDICINE, AS ACTS (True, 2026-10-03, written by hand from lib/data's record — each signature's "what it is" and balanced face,
// read through to what a person DOES when that capacity is well). Founder: the medicine is the entire key. The Pour's ask is the
// partner's own act, done small, in the seat; this is the partner's own act, said as acts, so the author has it in front of it on
// every call and the lint can check the ask against it.
//
//   acts   — plain verb phrases, each one a thing a camera could see a person do (or, for the inward ones, a thing they could truthfully
//            say they did). Never the status; never "find balance"; never speech by default.
//   people — true when the medicine's own face is about other people (then another person may be part of DOING the act).
//            Judged by the face, not the channel: Support (Structure) shares strength outward; Conscience (Resonance) is private.
//   seat   — one line on how the act bends when it lands in a part of a life, for the author.
//
// Keep each entry honest to the record. If a verb here is not in the signature's own description, it does not belong here.

export const MEDICINE_ACTS = {
  // ---- the twenty-two ----
  0:  { name: 'Potential',      people: false, acts: ['leave it undecided a while longer', 'meet the thing before you know what it is', 'start over as if for the first time', 'keep more than one door open on purpose', 'begin without a plan for the end', 'open the thing you have been assuming you knew and look at it unlabelled'] },
  1:  { name: 'Will',           people: false, acts: ['choose this, not that, and mean it', 'point your attention at one thing', 'decide from what is here now, not from habit', 'refuse the second thing so the first can have you', 'set a direction and take the first step in it'] },
  2:  { name: 'Wisdom',         people: false, acts: ['wait until you know which part matters, then begin with that part', 'notice what you already know before you reason about it', 'let a perception land without arguing it', 'sit with not knowing for ten minutes instead of filling it', 'attend to the one thing that is asking for attention and leave the rest', 'write the first thing you knew about it, before the reasons'] },
  3:  { name: 'Nurturing',      people: false, acts: ['tend it small and ask nothing of it', 'give it what it needs today, not what it is scheduled for', 'make room for it without steering it', 'keep showing up to it without forcing a result', 'protect the young thing from being judged early'] },
  4:  { name: 'Authority',      people: false, acts: ['give the mess a shape it can be carried in', 'set one rule that makes the rest easier', 'put a date, a place, a container on it', 'write the order things go in', 'build the smallest structure that holds it'] },
  5:  { name: 'Culture',        people: true,  acts: ['hand one thing on in the way you were handed it', 'join the practice the others keep', 'teach it the way it was taught to you, with one change', 'keep the ritual and give it room to change', 'learn how the people before you did it'] },
  6:  { name: 'Compassion',     people: true,  acts: ['sit with someone in it without fixing it', 'feel it alongside them and keep your own side', 'let yourself be reached by what they are carrying', 'stay in contact while it is hard', 'say what you see in them only if they ask'] },
  7:  { name: 'Drive',          people: false, acts: ['move toward the thing you want, one step, today', 'go where the feeling is already pulling', 'keep going through the next piece of resistance', 'put the energy you have into the direction you chose', 'start before you feel ready'] },
  8:  { name: 'Fortitude',      people: false, acts: ['carry it without tightening around it', 'hold your shape under the weight', 'keep it at its real size when you are asked to shrink it', 'bear the next hour of it without deciding anything', 'stay standing in it a while longer'] },
  9:  { name: 'Discipline',     people: false, acts: ['do the small practice again, alone, today', 'keep the session even when it feels pointless', 'refine one piece by repeating it', 'keep the steady light lit by attention, not flash', 'do the plain version first, before the plans'] },
  10: { name: 'Source',         people: false, acts: ['meet what is arriving as it arrives', 'let this moment be a fresh entry, not a continuation', 'notice what is newly here, right now', 'receive the thing that is coming instead of bracing for it', 'take the turning as it comes', 'open the door to the next thing on time, not early'] },
  11: { name: 'Equity',         people: true,  acts: ['give back what is owed, and take what is yours', 'put it in proportion, not in punishment', 'trade one thing for one thing, and keep no score', 'adjust the share until it is fair, then stop', 'let an exchange flow both ways'] },
  12: { name: 'Faith',          people: false, acts: ['let go of the thing you are gripping', 'release it on purpose, not by losing it', 'stop holding what no longer serves', 'surrender the outcome and keep the act', 'put it down and leave your hands empty a while'] },
  13: { name: 'Transformation', people: false, acts: ['let the thing end that is already over', 'close it, honour it, and do not reopen it', 'clear the space the ending leaves', 'mark the end of it with a plain act', 'let the old form go so the next one can come'] },
  14: { name: 'Tune',           people: false, acts: ['adjust one dial a little, then stop', 'add a little or take a little away, and sense the difference', 'find the centre and hold it while things move', 'rebalance by small corrections, not a lurch', 'blend the two things instead of choosing one'] },
  15: { name: 'Abstraction',    people: false, acts: ['trace the pattern across the last few times', 'see how it works underneath, apart from this instance', 'draw the shape of it without the details', 'name the mechanism in one line and change nothing', 'step back far enough to see the whole arrangement'] },
  16: { name: 'Breakthrough',   people: false, acts: ['stop holding up the false thing and watch it come down', 'let one structure collapse that could not hold', 'break the habit that was propping it', 'clear the ground of what came down', 'stand in the gap it leaves without rebuilding yet'] },
  17: { name: 'Inspiration',    people: false, acts: ['move toward the thing you actually want', 'choose the light to steer by and turn toward it', 'pick the one you would be sorriest to lose', 'let yourself want it, plainly, to yourself', 'remember what drew you and face it again'] },
  18: { name: 'Imagination',    people: false, acts: ['picture it a year on, turned out well, and keep the picture', 'take the next step with only enough light for that step', 'let the path show itself instead of forcing clarity', 'dream it from what you have already lived', 'move through the fog without demanding the map', 'sketch the whole of it badly, on one page, and keep the sketch'] },
  19: { name: 'Actualization',  people: false, acts: ['be what you already are, in your acts', 'do the thing in your own way, without proving it', 'let what you are show without dimming it', 'stop performing and simply do it', 'put your own name on what is already yours', 'do one thing today the way only you do it, and do not explain it'] },
  20: { name: 'Recognition',    people: false, acts: ['look at the same thing longer, until it shows you more', 'see the whole pattern you are standing inside', 'know it more deeply instead of newly', 'notice what is true across every layer of it', 'recognise where you are in the whole of it', 'draw the whole arrangement you are inside, with yourself marked on it'] },
  21: { name: 'Creation',       people: false, acts: ['finish the thing that has been waiting on its last step', 'close the cycle and leave the door open for the next', 'complete it without making it final', 'gather what it became and set it down whole', 'let the finished thing be the start of something'] },
  // ---- the forty bounds (the parent's act, at this scale and face) ----
  22: { name: 'Activation',     people: false, acts: ['catch the first spark before you point it anywhere', 'begin the thing while it is still nothing in particular', 'light it and do not decide yet what it is for', 'let the impulse start without a plan'] },
  23: { name: 'Orientation',    people: false, acts: ['choose which star to steer by and steer', 'turn toward the one direction and stop surveying', 'decide the heading from what you want, not from logic', 'face one way for three days'] },
  24: { name: 'Assertion',      people: true,  acts: ['declare the shape of it outward, plainly', 'claim the structure as yours in the open', 'put the frame on the table before anyone asks', 'state the order of things once, without argument'] },
  25: { name: 'Alignment',      people: false, acts: ['move at the pace your feeling can sustain', 'let the will and the wanting go the same way', 'keep the momentum steady instead of surging', 'find the rhythm and stay in it', 'do the next piece at the speed you can keep for a month, not the speed you can keep for a day'] },
  26: { name: 'Dedication',     people: false, acts: ['let the friction test what you are committed to', 'drop the wrong approach and keep the commitment', 'engage the hard part on purpose and see what holds', 'release the method, not the purpose'] },
  27: { name: 'Honor',          people: true,  acts: ['do the giving in the open this time, where it was always done unseen', 'do the next piece of it in front of the person it is for', 'stand where the giving can be witnessed', 'accept the acknowledgment when it comes', 'let what you gave up be seen by the people it was for, without a word about it', 'make the sacrifice visible without explaining it'] },
  28: { name: 'Resolve',        people: false, acts: ['defend the direction you chose against the next push', 'gather your determination and hold the line', 'keep the heading when it is contested', 'refuse the pull off course, once more'] },
  29: { name: 'Command',        people: false, acts: ['decide it and act the same day, without explaining', 'move with the clarity that needs no assertion', 'let the structure act instead of announcing it', 'make the call and carry it through'] },
  30: { name: 'Resilience',     people: false, acts: ['keep following the star after everything that has happened', 'carry on with the version you chose through another week of doubt', 'persist on hope that has been tested', 'go on toward it without needing a sign'] },
  31: { name: 'Realization',    people: false, acts: ['carry what the spark became to its full size', 'bring the possibility all the way into form', 'complete what you began by beginning it', 'let what was only possible stand finished'] },
  32: { name: 'Perception',     people: false, acts: ['look before you interpret', 'see the thing as if for the first time', 'make the first cut of seeing and stop there', 'notice what is before your eyes before naming it', 'describe what is in front of your eyes in five plain lines, no conclusions'] },
  33: { name: 'Reflection',     people: false, acts: ['hold two true things without declaring either', 'pause before you let it be known', 'weigh what you know before it leaves you', 'keep the truth a while before saying it', 'write both sides of it on one page and close the page'] },
  34: { name: 'Calculation',    people: false, acts: ['work the pattern through to its logic', 'cut through the story to what actually follows', 'count it out and read what the numbers show', 'reason it from first principles once'] },
  35: { name: 'Repose',         people: false, acts: ['let the mind rest instead of working the problem', 'sit still until the calibration settles', 'stop adjusting for an hour', 'rest in the balance you already have', 'put the problem down and take a walk with nothing to solve'] },
  36: { name: 'Honing',         people: false, acts: ['sort what matters from what does not, carefully', 'refine one distinction by close attention', 'strike one thing from the list that does not serve', 'sharpen the one skill by repeating its hardest part'] },
  37: { name: 'Guidance',       people: true,  acts: ['show someone the way you found', 'walk the route with someone who is lost on it', 'give directions plainly, once, and let them walk', 'point to the passage you can see'] },
  38: { name: 'Reconciliation', people: false, acts: ['gather the scattered thoughts into one line', 'bring the two sides of your thinking into one plan', 'reconcile what you know with what you feel about it', 'sort the pieces into a shape you can act on'] },
  39: { name: 'Immersion',      people: false, acts: ['go all the way into the pattern until you meet its edge', 'follow the thought past where it is comfortable', 'stay in the depth of it instead of surfacing', 'let the mind find its own limit in the thing', 'read the hardest page of it twice, slowly, before you stop'] },
  40: { name: 'Discernment',    people: false, acts: ['hold many truths at once without collapsing them', 'sort the kinds of pull from one another', 'let several things be true and act on one', 'distinguish what is yours from what you borrowed', 'list the pulls on you and mark which are yours'] },
  41: { name: 'Clarity',        people: false, acts: ['see it whole, with nothing hidden', 'see the true thing whole, as the last word on it', 'look at the whole of it until nothing is left to see', 'let the seeing be complete', 'lay every piece of it out where you can see all of it at once'] },
  42: { name: 'Receptivity',    people: false, acts: ['open before anything has arrived', 'let the feeling in without deciding what it is', 'receive what comes, unprepared', 'leave the heart open and empty a while', 'sit somewhere new with nothing in your hands and let whatever comes, come'] },
  43: { name: 'Merge',          people: true,  acts: ['choose one connection and flow with it', 'join someone in the work so the two streams run as one', 'let the vision be shared with one other', 'meet someone in the middle and go on together'] },
  44: { name: 'Celebration',    people: true,  acts: ['share the joy with the people it belongs to', 'mark the good thing together, the day it happens', 'let the gladness go out to the room', 'celebrate with the others, not after them'] },
  45: { name: 'Reverie',        people: false, acts: ['sit with what the heart already knows', 'let the feeling settle into its own depth', 'rest in the connection without doing anything with it', 'stay with the quiet of it', 'spend an hour with the thing you love without a task attached to it'] },
  46: { name: 'Conscience',     people: false, acts: ['act on the private sense of what is right', 'keep your own count of what is owed, and pay it', 'do the fair thing where no one will see', 'let the inner compass decide the small case', 'return the small thing you owe before anyone asks'] },
  47: { name: 'Reciprocity',    people: true,  acts: ['give one thing and take one thing, in balance', 'accept what is offered for what you gave', 'return the favour at its true size', 'let the exchange with someone run both ways'] },
  48: { name: 'Allure',         people: false, acts: ['gather the feelings that might be felt and look at them', 'let yourself be drawn before you choose', 'hold the cloud of possible feeling without picking yet', 'follow the pull of what might be felt, a little way', 'go once toward the thing that draws you and see what it is up close'] },
  49: { name: 'Passage',        people: true,  acts: ['walk toward what connects, leaving what does not', 'go deeper into the shared thing than comfort allows', 'cross over to the people it actually requires', 'leave the hollow ritual for the living one'] },
  50: { name: 'Fulfillment',    people: false, acts: ['let the satisfaction of a finished thing land', 'enjoy what you imagined now that it is here', 'be full for an hour with what was already felt', 'savour the realised thing without reaching past it', 'use the finished thing for an hour instead of improving it', 'eat the meal you made and leave the kitchen as it is', 'walk through the thing you built and touch nothing'] },
  51: { name: 'Completion',     people: false, acts: ['feel the whole of it, all the colours at once', 'let the felt connection be complete', 'know the feeling fully before you move on', 'take in the whole rainbow of what you feel', 'name every feeling in it on one page, none of them crossed out'] },
  52: { name: 'Definition',     people: false, acts: ['hold the first resource in your hand before investing it', 'define the seed of what will be built, in one line', 'decide what this is for before you spend it', 'name the form it will take, and only that'] },
  53: { name: 'Stewardship',    people: false, acts: ['tend the resource with responsible care', 'balance the competing demands and keep tending', 'look after what grows with a steady hand', 'steward it without clutching'] },
  54: { name: 'Formation',      people: false, acts: ['build the first new thing from what the clearing showed', 'make something skilled and small on the cleared ground', 'form the new structure with your hands', 'start building where the false thing fell'] },
  55: { name: 'Preservation',   people: false, acts: ['keep what the change produced from drifting', 'hold the new form steady', 'protect what was won by the ending', 'set the finished thing down in a form that keeps'] },
  56: { name: 'Steadfastness',  people: false, acts: ['persist on your own reserves through the pressure', 'keep going without checking on anyone else', 'carry your own share, all of it', 'stand firm in the material hardship'] },
  57: { name: 'Support',        people: true,  acts: ['share your strength where it is needed', 'give a concrete piece of help and finish it', 'let resources flow to the person who needs them', 'hold someone else up with what you have'] },
  58: { name: 'Harvest',        people: false, acts: ['gather what the change grew', 'count what the ending gave you', 'take in the yield of what was transformed', 'collect the fruit of the patient wait'] },
  59: { name: 'Commitment',     people: false, acts: ['keep building the thing with sustained craft', 'deepen the mastery by persisting at it', 'return to the work daily until it is profound', 'commit to the long build and do today\'s part'] },
  60: { name: 'Flourishing',    people: false, acts: ['enjoy what careful tending produced', 'let the abundance be seen and used', 'take pleasure in the grown thing', 'rest in the result of the tending'] },
  61: { name: 'Achievement',    people: false, acts: ['establish the thing that lasts', 'finish the legacy by sustained will', 'complete the form so it stands without you', 'bring the directed work to its full standing'] },
  // ---- the sixteen agents (the parent as behaviour) ----
  62: { name: 'Initiate of Intent',     people: false, acts: ['start something for the spark of starting', 'explore a direction before it has a destination', 'express yourself freshly, with confidence', 'ask the beginner\'s question about where to go'] },
  63: { name: 'Catalyst of Intent',     people: false, acts: ['cut through the inertia with one decisive act', 'set a boundary and hold it', 'charge forward on the decision you made', 'lead the change by moving first'] },
  64: { name: 'Steward of Intent',      people: false, acts: ['tend the fire without burning out', 'keep the motivation warm with steady care', 'hold the direction with courage, day after day', 'feed the drive a little at a time'] },
  65: { name: 'Executor of Intent',     people: false, acts: ['release what is done and keep what is not', 'bear the duty and know when to let go', 'drop one condition you set and take the step', 'govern by knowing what to surrender'] },
  66: { name: 'Initiate of Cognition',  people: false, acts: ['listen as a student of it', 'follow a raw curiosity with no use for it', 'ask the question you do not know the answer to', 'perceive it with fresh eyes before judging'] },
  67: { name: 'Catalyst of Cognition',  people: false, acts: ['reason it through fast and cleanly', 'cut to the logic and act on it', 'strategise the next three moves', 'think it through to its sharp point'] },
  68: { name: 'Steward of Cognition',   people: true,  acts: ['tell the truth with care for when and how', 'calibrate what you say to what can be heard', 'hold the clarity steady and tempered', 'say the hard thing gently, once'] },
  69: { name: 'Executor of Cognition',  people: false, acts: ['write the facts down in order, without feeling words', 'apply the method rigorously, once', 'judge it by the discipline, not the mood', 'put the inquiry on paper and follow it'] },
  70: { name: 'Initiate of Resonance',  people: false, acts: ['sense what has not happened yet, with wonder', 'envision it freshly and feel toward it', 'explore the feeling with fresh sensitivity', 'dream the next step and take it'] },
  71: { name: 'Catalyst of Resonance',  people: true,  acts: ['pursue the emotional truth with someone', 'make a ritual of the shared thing', 'quest after the connection in the open', 'teach what you feel by doing it with others'] },
  72: { name: 'Steward of Resonance',   people: true,  acts: ['hold space for what someone feels without fixing it', 'ask how it feels to them and stay with the answer', 'keep the connection coherent while it is hard', 'be present to their feeling without drowning in it'] },
  73: { name: 'Executor of Resonance',  people: true,  acts: ['make the fair call about a feeling, yourself', 'judge the hurt fairly after it has finished', 'govern the feeling with principle, not reaction', 'weigh what it costs them against what it gives'] },
  74: { name: 'Initiate of Structure',  people: false, acts: ['learn how it grows by tending it', 'apprentice yourself to the material thing', 'care for it with fresh hands and see what it needs', 'tend the small thing and learn from it'] },
  75: { name: 'Catalyst of Structure',  people: false, acts: ['force the change into reality by steady effort', 'pioneer the new ground slowly and without stopping', 'move the structure one real inch', 'build the change by persistent work'] },
  76: { name: 'Steward of Structure',   people: false, acts: ['release what is done and keep what serves', 'provide for the growth by knowing what to let go', 'maintain the abundance by clearing what is finished', 'keep the material thing sustainable'] },
  77: { name: 'Executor of Structure',  people: false, acts: ['build the thing that endures', 'hold the weight as a builder holds stone', 'stabilise it with embodied strength', 'lay the one step you can see, solidly'] },
};

/** The partner's acts as a line for the plan, or '' when the id is unknown. */
export function medicineActsLine(partnerId) {
  const m = MEDICINE_ACTS[partnerId]; if (!m) return '';
  return `the medicine, as acts (${m.name} does these when it is well — the ask is one of them, done small, in this seat${m.people ? '; this medicine is about people, so another person may be part of the act' : '; this medicine is the person\'s own, so no one else is needed for the act'}): ${m.acts.join(' · ')}`;
}

/** Whether the medicine is about other people, by its face (for the people rule). */
export function medicineIsAboutPeople(partnerId) { return !!MEDICINE_ACTS[partnerId]?.people; }
