// THE POUR — schema v0.5 (2026-09-30, gaveled by the founder item by item: DECISIONS_Chris_The_Pour_Line_v2_Gaveled_2026-09-30).
// A CELL is one signature in one seat at one status, authored once by a seated strong model, checked, and served as the
// floor the live Reader stands on. The four load-bearing parts live in four grammatical roles so a paraphrase cannot
// collapse them (Keel): the status as a TENSE, the card as a VERB phrase, the seat as a PLACE phrase, the ask as an OFFER
// with an object. The medicine is the heart of every cell: the ask derives from the PARTNER and its mechanism, never from
// the status alone (provenance mandatory). Cells are scalar (one status); the vector and etiology are assembler data.

export const SCHEMA_VERSION = '0.5';
export const PROMPT_VERSION = 'pour-author-2026-10-02-g';   // g: plain human terms — most cells carry no image at all; the healthy picture is an everyday action, not a metaphor; the ask's examples un-named   // f: e with the sins un-named — the principles stay, the barred words live only in the lints (a small model copies what a rule quotes)   // e: after two strangers (Gemini Deep Think, GPT Pro) read set D cold — the card's claim not the person's verdict; the ask is an experiment a camera could see; the difficulty; no nominalisation; the author's own check before the cells   // d: after three judges on C — the sheet line is one beat again, the healthy picture is one sentence in the seat's own image and may come second, the wound by paraphrase and durations are named, contractions, no instruction words, the partner's name once   // c: the human face — said across a table, the situation before the fault, done-well first, the way back plain, now in it   // b: after Keel's wave-one picks — verb and place once per call; the wound, the person, the labels, the refrains, the weave

export const STATUS_KEYS = { 1: 'balanced', 2: 'tooMuch', 3: 'tooLittle', 4: 'unacknowledged' };
export const STATUS_NAMES = { 1: 'Balanced', 2: 'Too Much', 3: 'Too Little', 4: 'Unacknowledged' };

// what the author returns, per status, and what the library stores
export const CELL_FIELDS = {
  tense: 'one sentence — where in time this person is standing, in plain words (future-facing / past-anchored / disowned-present / now, with the pen). First sentence of the cell.',
  verb: 'the card as a verb phrase — what this capacity DOES, in the person ("the part of you that tends what is growing"). Never the seat.',
  place: 'the seat as a place phrase — WHERE in a life this is happening ("in the part of your life where you see how things work"). Never the card.',
  ask: 'the medicine, from the PARTNER card and its mechanism, as an offer with an object — one real thing, sized to today, that the person may take or leave, as it looks IN THIS SEAT. Under 40 words. Closes on what it gives back, in fresh words each time. Never an order.',
  core: 'the four above, said to the person across a kitchen table, 120 to 160 words, two short paragraphs. First what this capacity looks like in this part of their life when it is going well (there is always such a picture), then how the status is bending it now, then the way back in plain words and what it gives back. Second person, present tense, short sentences, the way a friend who knows the map would say it — not written prose. The ask is re-said inside it in different words, never pasted.',
  sheetLine: 'one line a person could carry out of the room, under 18 words, no semicolon: the situation as one beat, said the way you would say it ("You keep getting it right and calling it luck."). The three beats belong in the core, not here.',
};

// what rides into every authoring call besides the record: the seat (the Crossing + the room), these rules, the exemplars
export const CELL_RULES = `THE CELL — what you are writing, and the rules it is held to (each one checked by a machine before the cell enters the library):

1. FOUR PARTS IN FOUR ROLES. The status as a TENSE (first sentence). The card as a VERB phrase. The seat as a PLACE phrase. The ask as an OFFER with an object. Keep them in those roles; a cell where the card and the seat could swap places is a failed cell.
2. THE ASK IS THE PARTNER'S, AND IT LANDS IN THE SEAT. The medicine in every cell is the partner card's own action, by its mechanism (diagonal / vertical / reduction / growth), given in the record beneath. Never the status alone, never "be more balanced", never the drawn card prescribing itself. The same partner's act looks different in different seats — "name the hope" in the part of a life that moves is a different act from "name the hope" in the part that endures — so the ask says what the act looks like HERE; an ask that would serve any seat with a noun swapped is a failed ask. Under 40 words. Close on what it gives back, in words you have not used before.
3. BALANCED IS NOT A DIPLOMA. A Balanced cell carries a growth vector and an ask — what this balance is free to feed next. "You made it" is a failed cell.
4. KITCHEN TABLE. No house names, no channel names, no status words as jargon, no stage words, no card names other than the drawn card's, no "expressed through", no elements as elements, no "medicine", no "the map", no "the Reader", no tarot words (no star, no cup, no sword). Say the plain thing: "the empty tank" means nothing to a stranger; "trying harder at the thing that's gone quiet doesn't work" does. Precision is measured in what the sentence entails, never in vocabulary.
5. CONDITION, NOT VERDICT. Tenses, never diagnoses. No anxiety, depression, trauma, disorder, narcissist, codependent, burnout, healing as labels. No worth-words about the person.
6. NO HUNCHES, NO HISTORY, NO WOUND. A cell knows the card, the seat and the status. It does not know this person. No "you learned early", no "years ago", no "months now", no sister, no scene, no motive ("for safety", "for an audience"). Too Little may locate the person behind the present; it may not say what happened there, who caused it, how long ago, what it cost them, who failed them, or what lesson they took from it — in any wording. The card does not say so and the person never did. The clean form is a location with no story in it. Where the live Reader will later ask, the cell leaves room; it never guesses.
7. AN OFFER, NEVER AN ORDER. No "you must", "you should", "you need to", "you have to". The ask is phrased so the person owns it.
8. USUALLY NO PICTURE. Most cells need no image at all: say the feeling and the action in plain human words — tired, relieved, stalling, proud, avoiding, glad. If one image earns its place, it is one, carried through, and it is the only one in the cell; a second image, or a world of rooms and doors and benches and shapes, turns the cell into a parable a stranger has to decode, and they stop reading.
9. THE PARENT, NOT THE PICTURE. A Bound or an Ambassador is its parent archetype's capacity through a channel at a number, or in a role; the record names the parent. Nothing from any card's picture or any inherited tradition.
10. SAY IT ONCE, WARM. Written by someone, to someone, once. Plain is not cold: acknowledge the weight in the tense, offer rather than assign, stay a beat. Warmth is in the stance, never in adjectives or stock phrases.
11. NO "I", NO "SHE". A cell has no first person — the Reader may add one live; the floor may not. No he, she, him or her for the partner or for anyone: the partner is a capacity, not a person, and the reader's own pronoun is theirs.
12. SENTENCES, NOT LABELS. The tense line is a sentence of at least six words about where this person is standing in time — never "Present —", "Past:", "Disowned present", and never "Offer:" before an ask. The record's words for the statuses do not appear anywhere.
13. YOUR OWN SENTENCES. The exemplars show the register; not one of their sentences, and no five words in a row from them, appear in a cell. A person who draws twice must not meet the same sentence twice, so the closing phrase, the tense line and the way the medicine is handed over are yours, new, each time. Vary the tense line by seat.
14. WOVEN, NOT PASTED. The core re-says the ask in other words; it never contains the ask sentence whole, and it never leaves the ask out. Two paragraphs, a blank line between them.
15. THE SITUATION, NOT JUST THE FAULT. Every card belongs in every seat, so the core says what this looks like in this part of their life when it is going well — there is always such a picture, at every status — as well as how the status is bending it now. The healthy picture is ONE sentence, an everyday action in this part of a life said plainly (what the person does on an ordinary day when this is going well), not a metaphor for it, and it may come first or second; it never opens on a stock hinge that announces the healthy picture before giving it — walk in on the picture itself. Vary the order from cell to cell. A cell that is only a fault leaves the person nothing to stand on; a cell that opens the same way every time is a factory.
16. SAID, NOT WRITTEN. This core is read by a person, across a table, in your voice — not only by a machine. Short sentences. No aphorisms: a sentence that would look good on a poster ("that's not a ceremony, it's a receipt") is a sentence admiring itself; say the plain thing instead. Contractions: you're, it's, doesn't, can't — the way people talk; "you are" and "it is" and "cannot" are the written voice and a machine counts them. Say the thing and then the next thing. No stacked images, no aphorisms, no sentence that admires itself. The core's first sentence carries the tense in different words from the tense line, never the tense line pasted. If you would not say it out loud to someone you like, do not write it.
17. NOW. The way back is taken today or not at all — last month's choosing cannot be changed and next month's cannot be pre-signed. Say the ask in that size, once, in your own words — as a condition, never an ultimatum — and say plainly what it is: the way back, from the partner's own act, named in words a stranger can hear.
18. THE PARTNER'S NAME, ONCE OR NOT AT ALL. The partner card may be named once, as a name ("the way back here is what Honor does"), never as a common noun ("Authority is what's needed"), never as a label ("offer Passage:"), and never as a sentence of its own fruit grafted whole from its record. Your own words for the act, in this seat.
19. NOT THE AUTHOR'S WORDS. "Capacity", "this part of a life", "the seat", "the map", "the status" are this package's words for talking to you. None of them reaches the person.
20. THE CARD'S CLAIM, NOT THE PERSON'S VERDICT. Be specific about what the person might recognise without pretending to know more about their life than the record establishes; let the newness come from a useful distinction or an unexpected next step, never from a more dramatic claim about who they are. The status is a condition of one capacity in one part of a life — a reason to look for a pattern, not proof of the person's history, motives, feelings or circumstances. So: no universals — no sentence about what the person always does, never does, or what everyone around them feels; no certifying the person — no telling them their knowing has been accurate, that they already know the answer, that what they do costs them nothing; no contradicting a feeling with a deeper truth you supplied; no hidden reason stated as fact — the cell never says what is "really" under the person's behaviour, what fear drives it, what the real problem is beneath the apparent one, or what "happened the last time"; no praising the person for a method you invented for them (how they built it, what they tested, what they chose), and no example of their life presented as proof; no making the current behaviour foolish to sell the alternative — preparation can be useful, persistence can be necessary, privacy can be chosen, an unfinished thing may really be unfinished. Narrow the claim instead of hedging it: "preparing for a conversation doesn't give you the other person's answer" is true of the capacity and leaves the person's biography alone. A reader must be able to say "no, that's not what's happening" and still have something to use. The ask never makes progress conditional on obeying it — "that only happens when you…" is a door closing.
21. THE ASK IS AN EXPERIMENT A CAMERA COULD SEE. One act, in the physical world, with a finish, doable today without spare money, spare energy, a safe person on hand or freedom from obligations — something they could do at the table they are sitting at, in their own words for it, never a stock exercise. Never an emotion or a state as an instruction — wanting, trusting, releasing, a quieter mind are results, not acts; the act is what someone could watch them do. A good experiment teaches the person something even if the reading is wrong about them, and it never promises what it will fix. Say what it gives back as a possibility, in fresh words.
22. THE DIFFICULTY. Name, in one clause, what makes this hard beyond the name of the condition — what the present behaviour might be preserving, what changing it might cost — as a possibility, never as the person's hidden motive. Balanced is not costless: a person doing this well is still carrying something, and the cell says what.
23. PLAIN VERBS, PLAIN NOUNS. Keep verbs as verbs: a person sees, knows, tends, holds, becomes — the cell never makes a noun of that with "the" or "your" in front of it to sound deep, and never asks a vague "the thing" to carry a meaning the cell has not established. If an image is used at all, it is something in a life, never something ethereal — and see rule 8: usually none. Outside Unacknowledged, the cell does not tell the person they are doing one thing and calling it another. The ask is not the same ask as the last cell's; the close is not the same close. A machine checks every cell for the house's known tics and sends it back when it finds one; your part is to say it your own way.
24. THE OPENING EARNS ITS FORCE. The sheet line opens something worth noticing — a tension, a precise distinction, a permission — not a verdict on the person's whole life, and it need not begin with "You". The core's first sentence need not either. Vary the entrance from cell to cell.
25. YOUR OWN CHECK, BEFORE YOU WRITE THE CELLS. In the "check" field, first, in two or three plain sentences: which personal claim in your draft lacks support in the record; what the reader might reasonably say is different; whether the ask is still useful if your read is wrong; which sentence serves the writer more than the reader. Then write the cells so the answers are already fixed. The check never reaches the person.`;

export const RESPONSE_SHAPE = `Respond with ONLY a JSON object, nothing outside it, paragraph breaks inside strings written as the two characters backslash-n:
{"check": "your own check first (rule 25): the unsupported claim, the reader's likely objection, whether the ask survives being wrong, the sentence that serves the writer — two or three plain sentences; never shown to the person",
 "verb": "the card as a verb phrase — written ONCE; it is the same card at every status",
 "place": "the seat as a place phrase — written ONCE; the seat does not move because the person is braced or behind",
 "cells": [
  {"status": 1, "tense": "...", "ask": "...", "core": "...", "sheetLine": "..."},
  {"status": 2, "tense": "...", "ask": "...", "core": "...", "sheetLine": "..."},
  {"status": 3, "tense": "...", "ask": "...", "core": "...", "sheetLine": "..."},
  {"status": 4, "tense": "...", "ask": "...", "core": "...", "sheetLine": "..."}
]}
The four cells are four faces of one thing: the same card in the same seat, at the four statuses. Only the tense and the ask move between them. Too Much and Too Little must read as opposite failures of one capacity.`;
