// === CORE DATA: ARCHETYPES, BOUNDS, AGENTS ===
// The 78 signatures of the Nirmanakaya system
//
// STRUCTURAL IDENTITY: Every signature carries its full derivative chain.
// Archetypes: direct structural position (house, channel, function, governance)
// Bounds: parent archetype × element × number scale
// Agents: parent archetype × element × role
//
// THREE STRUCTURAL DIMENSIONS OF EVERY BOUND:
//   Horizon (from number):  1-5 = inner (what archetype IS at rest)
//                           6-10 = outer (what archetype DOES in action)
//   Scale (from number):    1-3 = formative, 4-7 = operative, 8-10 = completive
//   Number House (from number pair): 1&10=Gestalt, 2&9=Spirit, 3&8=Mind, 4&7=Emotion, 5&6=Body
//
// Agent horizon = parent archetype's creation/operation phase (0-9=inner, 11-20=outer)

export const ARCHETYPES = {
  // TRANSIENT STATES: Archetype-specific behavioral descriptions for each of the 4 statuses.
  // Derived from Nirmanakaya architecture, validated against Curtiss convergence evidence (March 2026).
  // These replace generic status labels with precise behavioral portraits for interpretation and RLHF.

  0: { name: "Potential", traditional: "The Fool", house: "Gestalt", channel: null, function: "Seed",
       description: "Pure possibility before differentiation",
       extended: "The seed state of all becoming. Not naivety but infinite potential — the moment before choice collapses possibility into actuality. Contains everything, committed to nothing yet.",
       states: {
         balanced: "Pure presence — open, available, ready. Beginner's mind. Every moment fresh",
         tooMuch: "Hovering in endless possibility, never landing. All potential, no actualization",
         tooLittle: "Past wounds have sealed the opening. Creating from constriction",
         unacknowledged: "Operating reactively without seeing options — doors invisible"
       } },
  1: { name: "Will", traditional: "The Magician", house: "Gestalt", channel: null, function: "Bridge",
       description: "Directed agency, choosing direction",
       extended: "The capacity to direct attention and energy toward chosen ends. Not force but focused intention — the ability to say 'this, not that' and mean it.",
       states: {
         balanced: "Conscious direction aligned with Now — choosing from clarity, not compulsion",
         tooMuch: "Future-projected control — manipulation, forcing outcomes, white-knuckling reality",
         tooLittle: "Past-anchored defeat — passivity, \"what's the point,\" learned helplessness",
         unacknowledged: "Direction without awareness of directing — drifting with momentum, confusing habit for choice"
       } },
  2: { name: "Wisdom", traditional: "The High Priestess", house: "Spirit", channel: "Cognition", function: "Seed",
       description: "Knowing what to attend to",
       extended: "Deep knowing that precedes analysis. The capacity to recognize what matters before understanding why. Wisdom isn't accumulated knowledge — it's seeing through to essence.",
       states: {
         balanced: "Direct knowing that proves accurate — comfort with not-knowing; perceptions land without argument",
         tooMuch: "Information hoarding, analysis paralysis — the veil becomes a wall",
         tooLittle: "Chronic confusion, lost faith in perception — seeking external validation for what you already know",
         unacknowledged: "Perceptions that prove accurate but surprise you — insights shape decisions you believe are random"
       } },
  3: { name: "Nurturing", traditional: "The Empress", house: "Spirit", channel: "Structure", function: "Bridge",
       description: "Care for what is growing",
       extended: "Tending what needs to develop. Creating conditions for growth without forcing outcomes. The patient attention that allows emergence.",
       states: {
         balanced: "Growth happening without forcing — care that doesn't exhaust; holding space without clutching",
         tooMuch: "Controlling under the guise of care — smothering, martyrdom, boundary dissolution",
         tooLittle: "Chronic creative block, nothing grows — emotional unavailability disguised as independence",
         unacknowledged: "Nurturing roles you never chose — others experience you as caretaker while you feel depleted"
       } },
  4: { name: "Order", traditional: "The Emperor", house: "Mind", channel: "Intent", function: "Seed",
       description: "Establishing pattern and structure",
       extended: "The impulse to organize chaos into workable form. Not rigid control but functional architecture — creating containers that allow complexity to be navigated.",
       states: {
         balanced: "Structure that serves what it organizes — clear, reliable; things make sense in your presence",
         tooMuch: "Rigid over-organization, control — mistaking the throne for the kingdom",
         tooLittle: "Chronic disorganization — can't prioritize, can't sequence; the pieces never assemble",
         unacknowledged: "Organizing without knowing you're organizing — others rely on your structure while you feel formless"
       } },
  5: { name: "Culture", traditional: "The Hierophant", house: "Mind", channel: "Resonance", function: "Bridge",
       description: "Shared meaning and tradition",
       extended: "The transmission of meaning across time and between people. Rituals, languages, practices that carry wisdom forward. Living connection to what has proven valuable.",
       states: {
         balanced: "Living transmission of meaning — teaching that adapts; tradition that breathes; belonging without conformity",
         tooMuch: "Rigid orthodoxy, dogma — conformity demanded; the letter kills the spirit; windows sealed",
         tooLittle: "Rootless, no shared framework — every generation reinventing the wheel; lonely intelligence",
         unacknowledged: "Transmitting without knowing it — you're already the teacher; you just don't see it"
       } },
  6: { name: "Compassion", traditional: "The Lovers", house: "Emotion", channel: "Resonance", function: "Seed",
       description: "Relational connection and alignment",
       extended: "The capacity to feel with rather than just about. Genuine alignment between beings that recognizes shared experience. Connection that honors difference.",
       states: {
         balanced: "Felt recognition that honors both self and other — connection without fusion",
         tooMuch: "Emotional fusion, boundary dissolution — can't tell where you end and others begin",
         tooLittle: "Emotional numbness, disconnection — relationships stay surface",
         unacknowledged: "Deep connection disguised as indifference — others feel your compassion while you feel nothing"
       } },
  7: { name: "Drive", traditional: "The Chariot", house: "Emotion", channel: "Intent", function: "Bridge",
       description: "Directed momentum toward goals",
       extended: "Energy channeled toward destination. Not aggression but focused motion — the capacity to maintain direction through resistance without being consumed.",
       states: {
         balanced: "Movement from feeling — direction from genuine engagement",
         tooMuch: "Driving past the destination — momentum that can't stop",
         tooLittle: "Stalled at the threshold — feeling without forward motion",
         unacknowledged: "Momentum you don't know you have — or stagnation you can't see"
       } },
  8: { name: "Fortitude", traditional: "Strength", house: "Body", channel: "Structure", function: "Seed",
       description: "Endurance and holding capacity",
       extended: "The ability to bear what must be borne. Not hardness but resilient strength — capacity to hold form under pressure without breaking or becoming rigid.",
       states: {
         balanced: "Holding without forcing — capacity that contains rather than crushes",
         tooMuch: "Gripping past necessity — strength becoming rigidity",
         tooLittle: "Collapse under pressure — holding feels too dangerous",
         unacknowledged: "Strength or collapse you don't see in yourself"
       } },
  9: { name: "Discipline", traditional: "The Hermit", house: "Body", channel: "Cognition", function: "Bridge",
       description: "Focused practice and refinement",
       extended: "Solitary cultivation of capacity through repetition. The hermit's lamp illuminates through sustained attention, not flash. Intention transformed into embodied skill.",
       states: {
         balanced: "Practice flows without force — solitude connects rather than isolates; refinement serves growth, not anxiety",
         tooMuch: "Practice becomes perfectionism — isolation feels necessary rather than chosen; refining compulsively, fearing what happens if you stop",
         tooLittle: "Past experiences have made practice feel dangerous — chronic inability to sustain cultivation",
         unacknowledged: "You don't know you're practicing — or refusing to. Expertise arrives 'without trying'"
       } },
  10: { name: "Source", traditional: "Wheel of Fortune", house: "Portal", channel: null, function: "Ingress",
        description: "What is entering now",
        extended: "The turning point where what was outside enters the system. Not fate but timing — recognizing what's arriving and how to meet it.",
        states: {
          balanced: "You recognize yourself as the turning — each moment is fresh entry. Present-moment awareness as natural state",
          tooMuch: "The Wheel seems to turn you — fate replaces choice; patterns repeat without awareness; external locus of control",
          tooLittle: "Trying to step off the Wheel — spiritual bypassing, rejecting manifestation, clinging to fixed states",
          unacknowledged: "You don't know you're on the Wheel — surprise at obvious consequences; unconscious patterns cycling"
        } },
  11: { name: "Equity", traditional: "Justice", house: "Body", channel: "Resonance", function: "Fruition",
        description: "Fair calibration and balance",
        extended: "Right relationship made manifest. Not punishment but recalibration — adjusting what's out of proportion until balance returns.",
        states: {
          balanced: "Fairness flows naturally — clear sense of what's right without obsessive calculation; give and receive in flowing exchange",
          tooMuch: "Fairness becomes accounting — obsessive tracking of who owes what; relationships reduced to exchange calculations",
          tooLittle: "Chronic inability to claim what's owed — tolerance of unfair treatment; past experiences have made fairness feel dangerous",
          unacknowledged: "You don't know you're weighing — tallying grievances you didn't know you were counting"
        } },
  12: { name: "Sacrifice", traditional: "The Hanged Man", house: "Body", channel: "Intent", function: "Feedback",
        description: "Purposeful release",
        extended: "Conscious letting go of what no longer serves. Not loss but clearing — creating space by releasing grip. Revealing value hidden by habitual grasping.",
        states: {
          balanced: "Release flows naturally from completion — surrender as fulfillment, not defeat",
          tooMuch: "Releasing before completion — martyrdom, premature surrender, performative self-denial",
          tooLittle: "Inability to let go — exhaustion from chronic holding, controlling grip",
          unacknowledged: "Not knowing you've already surrendered — or that you haven't"
        } },
  13: { name: "Change", traditional: "Death", house: "Emotion", channel: "Structure", function: "Fruition",
        description: "Necessary endings and clearing",
        extended: "The completion that allows new beginning. Not destruction but transformation — the moment when what was must fully end for what will be to emerge.",
        states: {
          balanced: "Transformation flows from felt necessity — endings honored, renewal trusted",
          tooMuch: "Constant upheaval — ending things before they've lived, fear disguised as liberation",
          tooLittle: "Clinging to what's dead — stagnation disguised as loyalty, fear of all endings",
          unacknowledged: "Not knowing what's dying in you — or that anything is"
        } },
  14: { name: "Tune", traditional: "Temperance", house: "Emotion", channel: "Cognition", function: "Feedback",
        description: "Dynamic equilibrium",
        extended: "Continuous adjustment that maintains flow. Not static middle but active calibration — sensing when to add, when to subtract, how to blend.",
        states: {
          balanced: "Equilibrium flows from genuine integration — centered presence holding complexity",
          tooMuch: "Premature harmony — conflict avoidance, suppressing necessary distinctions",
          tooLittle: "Chronic fragmentation — inability to find center, scattered by every engagement",
          unacknowledged: "Not knowing how you're integrating — or that you aren't"
        } },
  15: { name: "Abstraction", traditional: "The Devil", house: "Mind", channel: "Cognition", function: "Fruition",
        description: "Pure pattern, freed from literal",
        extended: "Recognition of pattern stripped of content. Not temptation but clarity about mechanism — seeing how things work beneath surface appearance.",
        states: {
          balanced: "Conceptual depth flows from genuine understanding — seeing patterns that liberate",
          tooMuch: "Over-intellectualization — pattern-seeing that becomes paranoia, analysis without end",
          tooLittle: "Avoidance of depth — literalism, refusal of symbol, willful naivety",
          unacknowledged: "Not knowing how patterns bind you — or that they do"
        } },
  16: { name: "Breakthrough", traditional: "The Tower", house: "Mind", channel: "Structure", function: "Feedback",
        description: "Sudden clearing of false structure",
        extended: "Rapid dissolution of what couldn't hold. Not catastrophe but liberation — structures built on false premises collapse when truth arrives.",
        states: {
          balanced: "Destruction flows from genuine insight — structures fall that needed to fall",
          tooMuch: "Premature shattering — chaos disguised as liberation, unable to let anything stand",
          tooLittle: "Clinging to dead structures — maintaining the Tower past its usefulness",
          unacknowledged: "Not knowing what's about to fall — or that it should"
        } },
  17: { name: "Inspiration", traditional: "The Star", house: "Spirit", channel: "Intent", function: "Fruition",
        description: "Aspirational pull toward light",
        extended: "The draw toward what's genuinely desired. Not fantasy but orientation — knowing which star to steer by. Recognized, not given; remembered, not arrived.",
        states: {
          balanced: "Radiance flows from genuine development — shining because what was cultivated reached completion",
          tooMuch: "Chronic ungrounded optimism — projecting light forward in anxiety, dazzling rather than illuminating",
          tooLittle: "Spiritual exhaustion — cultivation that never flowers, hope defeated by experience",
          unacknowledged: "Not knowing you're radiating — or that you've stopped"
        } },
  18: { name: "Imagination", traditional: "The Moon", house: "Spirit", channel: "Resonance", function: "Feedback",
        description: "Navigating ambiguity",
        extended: "Capacity to move through uncertainty without forcing clarity. The moon illuminates enough to walk, not enough to see everything. Trust the path that reveals itself.",
        states: {
          balanced: "Vision flows from genuine integration — dreaming because experience has been fully processed",
          tooMuch: "Chronic illusion — confusing dream with reality, lost in symbolic depth",
          tooLittle: "Spiritual literalism — refusing depth, distrusting intuition, cutting off the symbolic",
          unacknowledged: "Not knowing what you're dreaming — or that dreams are shaping your life"
        } },
  19: { name: "Actualization", traditional: "The Sun", house: "Gestalt", channel: null, function: "Fruition",
        description: "Becoming what you are",
        extended: "Full expression of inherent nature. Not achievement but authenticity — allowing what you are to shine without dimming or distortion.",
        states: {
          balanced: "Radiance without ego — shining because you ARE light, not to prove it",
          tooMuch: "Solar inflation — mistaking the ray for the source, blinding others",
          tooLittle: "Solar eclipse — dimming what has been actualized, false modesty",
          unacknowledged: "Not knowing you're shining — or that you've stopped"
        } },
  20: { name: "Recognition", traditional: "Judgement", house: "Gestalt", channel: null, function: "Feedback",
        description: "Seeing the whole pattern",
        extended: "The capacity to perceive from outside the system while remaining within it. Not judgment but recognition — seeing what's true across all layers.",
        states: {
          balanced: "Recognition without finality — knowing that continues to deepen",
          tooMuch: "Rigid judgement — recognition becoming condemnation, spiritual arrogance",
          tooLittle: "Spiritual sleep — refusing the call, perpetual seeking that never lands",
          unacknowledged: "Not knowing that you know — or that you're refusing to know"
        } },
  21: { name: "Creation", traditional: "The World", house: "Portal", channel: null, function: "Egress",
        description: "Integration and completion",
        extended: "The point of departure that is also arrival. Full integration that allows release into next becoming. Completion that opens rather than closes.",
        states: {
          balanced: "Completion without finality — recognizing the cycle closes while remaining open to new cycles",
          tooMuch: "Premature completion — claiming arrival before the journey is done",
          tooLittle: "Perpetual incompletion — refusing to let cycles close, endless seeking",
          unacknowledged: "Not knowing that cycles have completed — or haven't"
        } }
};

export const BOUNDS = {
  // === INTENT CHANNEL (Fire/Wands) ===
  // Intent bounds express their parent archetype through directed will and action
  22: { name: "Activation", traditional: "Ace of Wands", channel: "Intent", number: 1, archetype: 0,
       house: "Gestalt", function: "Seed", horizon: "inner", wheelWorld: "Wheel", scale: "formative",
       numberKeyword: "Beginning/Perfection", numberHouse: "Gestalt",
       description: "Beginning of pure potential through Intent. The spark before direction.",
       extended: "Potential (0) expressed through Fire at the threshold of emergence. This is the moment undifferentiated possibility first catches fire — not yet pointed anywhere, not yet committed, but no longer dormant. The Ace is always the parent archetype at its most nascent: here, infinite possibility meets the Intent channel's demand for direction and produces the raw spark. Gestalt Seed through Fire: the whole self igniting before it knows what for. Inner bound — what Potential IS at rest before it moves. When this appears as a transient, something is trying to begin but hasn't found its shape yet." },
  23: { name: "Orientation", traditional: "2 of Wands", channel: "Intent", number: 2, archetype: 17,
       house: "Spirit", function: "Fruition", horizon: "inner", wheelWorld: "Wheel", scale: "formative",
       numberKeyword: "Balanced/Decisive", numberHouse: "Spirit",
       description: "Decisive direction through aspiration. Choosing which star to steer by.",
       extended: "Inspiration (17) expressed through Fire at the formative scale. The Star archetype gives aspirational pull — knowing which light to move toward. Through the Intent channel, this becomes decisive orientation: choosing a direction not from logic but from vision. Spirit Fruition through Fire: the mature harvest of inner knowing expressed as purposeful pointing. Number 2 is Balanced/Decisive — the inner face of the Spirit pair, where choice hasn't yet multiplied into abundance. This is direction-setting, not direction-defending. When this appears as a transient, the question isn't what to do but which calling to follow." },
  24: { name: "Assertion", traditional: "3 of Wands", channel: "Intent", number: 3, archetype: 4,
       house: "Mind", function: "Seed", horizon: "inner", wheelWorld: "Wheel", scale: "formative",
       numberKeyword: "Primal/Expansive", numberHouse: "Mind",
       description: "Primal claim of structure through Intent. Expansive declaration outward.",
       extended: "Order (4) expressed through Fire at the formative scale. The Emperor archetype organizes chaos into structure; through Intent, this becomes the assertive declaration of pattern outward into the world. Mind Seed through Fire: the first impulse to impose structure as a willed act. Number 3 is Primal/Expansive — the inner face of the Mind pair, where structure is broadcasting outward before it deepens. Assertion doesn't just establish order internally, it claims territory. When this appears as a transient, there's an urge to organize, to declare, to establish framework through forceful clarity." },
  25: { name: "Alignment", traditional: "4 of Wands", channel: "Intent", number: 4, archetype: 7,
       house: "Emotion", function: "Bridge", horizon: "inner", wheelWorld: "World", scale: "operative",
       numberKeyword: "Peace/Stillness", numberHouse: "Emotion",
       description: "Peaceful momentum, stable drive. Intent finding its natural rhythm.",
       extended: "Drive (7) expressed through Fire at the operative scale. The Chariot archetype channels emotional momentum toward goals; through Intent, this becomes aligned action — will and feeling moving in the same direction. Emotion Bridge through Fire: the sustained transmission of motivated energy. Number 4 is Peace/Stillness — the inner face of the Emotion pair, where Drive has found its groove before it needs to defend it. The four wands form a gateway, a celebration of momentum at rest in its own rhythm. When this appears as a transient, effort feels natural rather than forced; the doing is itself the reward." },
  26: { name: "Dedication", traditional: "5 of Wands", channel: "Intent", number: 5, archetype: 12,
       house: "Body", function: "Feedback", horizon: "inner", wheelWorld: "World", scale: "operative",
       numberKeyword: "Internal/Personal", numberHouse: "Body",
       description: "Internal practical release through Intent. Testing commitment through engagement.",
       extended: "Sacrifice (12) expressed through Fire at the operative scale. The Hanged Man archetype releases what no longer serves; through Intent, this becomes dedication tested through friction. Body Feedback through Fire: the integration that comes from letting go of the wrong approach and finding the right one through active engagement. Number 5 is Internal/Personal — the inner face of the Body pair, where the testing is private and personal. The five wands crossing are not public combat but internal clarification, burning away assumptions to reveal what you're actually committed to. When this appears as a transient, dedication is being pressure-tested behind closed doors." },
  27: { name: "Honor", traditional: "6 of Wands", channel: "Intent", number: 6, archetype: 12,
       house: "Body", function: "Feedback", horizon: "outer", wheelWorld: "World", scale: "operative",
       numberKeyword: "External/Shared", numberHouse: "Body",
       description: "External acknowledgment of sacrifice. Intent visible and honored.",
       extended: "Sacrifice (12) expressed through Fire at the operative scale. Same parent as Dedication (26) but at the outer face: where Dedication tests commitment internally, Recognition is commitment made visible and witnessed by others. Body Feedback through Fire: the cycle completes when what was sacrificed for is publicly honored. Number 6 is External/Shared — the outer face of the Body pair, where private effort becomes social acknowledgment. The victory parade, the laurel wreath — not ego gratification but the natural consequence of sustained release becoming visible achievement. When this appears as a transient, what was quietly given up is now seen and valued by the group." },
  28: { name: "Resolve", traditional: "7 of Wands", channel: "Intent", number: 7, archetype: 7,
       house: "Emotion", function: "Bridge", horizon: "outer", wheelWorld: "World", scale: "operative",
       numberKeyword: "Gathering/Reaping", numberHouse: "Emotion",
       description: "Gathered determination, harvested momentum. Defending chosen direction.",
       extended: "Drive (7) expressed through Fire at the operative scale. Same parent as Alignment (25) but at the outer face: where Alignment finds natural rhythm (inner/peaceful), Resolve defends it against resistance (outer/gathering). Emotion Bridge through Fire: the sustained transmission of motivated energy now facing opposition. Number 7 is Gathering/Reaping — the outer face of the Emotion pair, where all that was sown must be harvested or defended. Holding ground requires gathering everything that was scattered and directing it at the single point of defense. When this appears as a transient, something worth protecting is under pressure and the question is whether the momentum holds." },
  29: { name: "Command", traditional: "8 of Wands", channel: "Intent", number: 8, archetype: 4,
       house: "Mind", function: "Seed", horizon: "outer", wheelWorld: "Wheel", scale: "completive",
       numberKeyword: "Unfathomable/Deep", numberHouse: "Mind",
       description: "Deep authority, threshold structure. Intent moving with unstoppable clarity.",
       extended: "Order (4) expressed through Fire at the completive scale. Same parent as Assertion (24) but at the outer face: where Assertion declares structure outward (inner/primal), Command IS structure in motion — authority so complete it doesn't need to assert (outer/profound). Mind Seed through Fire: the initiating impulse of mental organization now operating at its deepest threshold. Number 8 is Unfathomable/Deep — the outer face of the Mind pair, where accumulated pattern achieves self-sustaining momentum. When this appears as a transient, decisions move with clarity and speed because the structural understanding is total." },
  30: { name: "Resilience", traditional: "9 of Wands", channel: "Intent", number: 9, archetype: 17,
       house: "Spirit", function: "Fruition", horizon: "outer", wheelWorld: "Wheel", scale: "completive",
       numberKeyword: "Abundance/Myriad", numberHouse: "Spirit",
       description: "Abundant persistence through aspiration. Strength from continued hoping.",
       extended: "Inspiration (17) expressed through Fire at the completive scale. Same parent as Orientation (23) but at the outer face: where Orientation chose which star to follow (inner/decisive), Resilience is still following it after everything that's happened (outer/abundant). Spirit Fruition through Fire: the mature expression of aspirational knowing now weathered but unbroken. Number 9 is Abundance/Myriad — the outer face of the Spirit pair, where a single decisive choice has multiplied into sustained endurance. The ninth wand is the one you lean on. When this appears as a transient, persistence itself has become a form of faith." },
  31: { name: "Realization", traditional: "10 of Wands", channel: "Intent", number: 10, archetype: 0,
       house: "Gestalt", function: "Seed", horizon: "outer", wheelWorld: "Wheel", scale: "completive",
       numberKeyword: "Completion/Finality", numberHouse: "Gestalt",
       description: "Completion of potential through Intent. Carrying what pure possibility became.",
       extended: "Potential (0) expressed through Fire at the completion of the cycle. Same parent as Activation (22) but at the outer face: where Activation was the spark before direction (inner/beginning), Realization is carrying what that spark became (outer/completion). Gestalt Seed through Fire: the whole self now bearing the full weight of what undifferentiated possibility materialized into through directed will. Number 10 is Completion/Finality — the outer face of the Gestalt pair, the widest span from beginning to end. The ten wands are heavy because they are real. When this appears as a transient, something that started as pure possibility has become a lived achievement, and the question is what to do with what you've created." },

  // === COGNITION CHANNEL (Air/Swords) ===
  // Cognition bounds express their parent archetype through mental clarity and understanding
  32: { name: "Perception", traditional: "Ace of Swords", channel: "Cognition", number: 1, archetype: 19,
       house: "Gestalt", function: "Fruition", horizon: "inner", wheelWorld: "Wheel", scale: "formative",
       numberKeyword: "Beginning/Perfection", numberHouse: "Gestalt",
       description: "Beginning of clear seeing. The first cut of clarity arising.",
       extended: "Actualization (19) expressed through Air at the threshold of emergence. The Sun archetype's radiant self-expression meets the Cognition channel's demand for clarity and produces the first cut of seeing — perception before content, the capacity to see before there's anything specific to see. Number 1 is Beginning/Perfection — the inner face of the Gestalt pair, the Ace's pristine potential. When this appears as a transient, a new clarity is trying to dawn; the sword is drawn but hasn't yet cut." },
  33: { name: "Reflection", traditional: "2 of Swords", channel: "Cognition", number: 2, archetype: 2,
       house: "Spirit", function: "Seed", horizon: "inner", wheelWorld: "Wheel", scale: "formative",
       numberKeyword: "Balanced/Decisive", numberHouse: "Spirit",
       description: "Decisive inner knowing. Mind holding truth before declaring it.",
       extended: "Wisdom (2) expressed through Air at the formative scale. The High Priestess archetype's deep knowing meets the Cognition channel and produces reflective discernment — weighing what is known before speaking. Spirit Seed through Air: the first stirring of mental wisdom. Number 2 is Balanced/Decisive — the inner face of the Spirit pair, where the mind holds two truths in balance before choosing. This is the pause before the declaration, the blindfolded figure with crossed swords — not indecision but deliberate withholding until the right moment. When this appears as a transient, wisdom is present but hasn't yet committed to a direction." },
  34: { name: "Calculation", traditional: "3 of Swords", channel: "Cognition", number: 3, archetype: 15,
       house: "Mind", function: "Fruition", horizon: "inner", wheelWorld: "Wheel", scale: "formative",
       numberKeyword: "Primal/Expansive", numberHouse: "Mind",
       description: "Primal analysis, expansive thought. Pattern recognition at work.",
       extended: "Abstraction (15) expressed through Air at the formative scale. The Devil archetype (pure pattern freed from literal) meets Cognition and produces calculation — logic cutting through illusion. Mind Fruition through Air: the harvest of pattern recognition expressed as thought. Number 3 is Primal/Expansive — the inner face of the Mind pair, where analysis is broadcasting outward before it deepens. This is logic at its sharpest and most exposed; it cuts whether you want it to or not. When this appears as a transient, a pattern has been recognized that changes understanding." },
  35: { name: "Repose", traditional: "4 of Swords", channel: "Cognition", number: 4, archetype: 14,
       house: "Emotion", function: "Feedback", horizon: "inner", wheelWorld: "World", scale: "operative",
       numberKeyword: "Peace/Stillness", numberHouse: "Emotion",
       description: "Peaceful stability through cognition. Mind at rest, calibrating.",
       extended: "Tune (14) expressed through Air at the operative scale. The Temperance archetype's dynamic equilibrium meets Cognition and produces mental repose — the mind finding stillness through calibration rather than activity. Emotion Feedback through Air: integrating emotional learning through thought. Number 4 is Peace/Stillness — the inner face of the Emotion pair, where the mind rests in its own balance before it needs to strategize. This is recovery through mental quieting — the knight lying still to heal. When this appears as a transient, the mind needs rest, not more thinking." },
  36: { name: "Discernment", traditional: "5 of Swords", channel: "Cognition", number: 5, archetype: 9,
       house: "Body", function: "Bridge", horizon: "inner", wheelWorld: "World", scale: "operative",
       numberKeyword: "Internal/Personal", numberHouse: "Body",
       description: "Internal practical cognition. Refining perception through careful distinction.",
       extended: "Discipline (9) expressed through Air at the operative scale. The Hermit archetype's focused practice meets Cognition and produces discernment — the capacity to distinguish what matters from what doesn't through rigorous attention. Body Bridge through Air: sustained disciplined thinking. Number 5 is Internal/Personal — the inner face of the Body pair, where the mental work is private and personal. This is the solitary thinker refining distinctions nobody else can see yet. When this appears as a transient, careful private analysis is needed before any public position." },
  37: { name: "Guidance", traditional: "6 of Swords", channel: "Cognition", number: 6, archetype: 9,
       house: "Body", function: "Bridge", horizon: "outer", wheelWorld: "World", scale: "operative",
       numberKeyword: "External/Shared", numberHouse: "Body",
       description: "External direction through discipline. Mind finding passage, showing the way.",
       extended: "Discipline (9) expressed through Air at the operative scale. Same parent as Discernment (36) but at the outer face: where Discernment refines distinctions privately (inner/practical), Guidance directs others toward clarity (outer/group). Body Bridge through Air: sustained disciplined thinking now serving others. Number 6 is External/Shared — the outer face of the Body pair, where private understanding becomes public direction. The boat crossing water — Discipline's careful perception charting passage for those who can't yet see the way. When this appears as a transient, what you know needs to become what you share." },
  38: { name: "Reconciliation", traditional: "7 of Swords", channel: "Cognition", number: 7, archetype: 14,
       house: "Emotion", function: "Feedback", horizon: "outer", wheelWorld: "World", scale: "operative",
       numberKeyword: "Gathering/Reaping", numberHouse: "Emotion",
       description: "Gathering thoughts into alignment. Strategic mental integration.",
       extended: "Tune (14) expressed through Air at the operative scale. Same parent as Repose (35) but at the outer face: where Repose rests in mental stillness (inner/peaceful), Reconciliation gathers scattered thoughts into strategic alignment (outer/gathering). Emotion Feedback through Air: integrating emotional learning through active mental work. Number 7 is Gathering/Reaping — the outer face of the Emotion pair, where the harvest of mental equilibrium requires effort to collect. When this appears as a transient, multiple lines of thought need gathering into a coherent strategy." },
  39: { name: "Immersion", traditional: "8 of Swords", channel: "Cognition", number: 8, archetype: 15,
       house: "Mind", function: "Fruition", horizon: "outer", wheelWorld: "Wheel", scale: "completive",
       numberKeyword: "Unfathomable/Deep", numberHouse: "Mind",
       description: "Deep threshold of abstraction. Mind exploring its own depths.",
       extended: "Abstraction (15) expressed through Air at the completive scale. Same parent as Calculation (34) but at the outer face: where Calculation cuts through with primal logic (inner/expansive), Immersion goes so deep into pattern that the mind encounters its own limits (outer/profound). Mind Fruition through Air: pattern recognition at its threshold. Number 8 is Unfathomable/Deep — the outer face of the Mind pair, where thought has gone as deep as thought can go. The bound figure is not trapped — they're immersed in the depths of their own abstraction. When this appears as a transient, thinking has reached a threshold where only a different kind of knowing can proceed." },
  40: { name: "Plurality", traditional: "9 of Swords", channel: "Cognition", number: 9, archetype: 2,
       house: "Spirit", function: "Seed", horizon: "outer", wheelWorld: "Wheel", scale: "completive",
       numberKeyword: "Abundance/Myriad", numberHouse: "Spirit",
       description: "Abundant knowing, many truths held. The fullness of perception.",
       extended: "Wisdom (2) expressed through Air at the completive scale. Same parent as Reflection (33) but at the outer face: where Reflection holds two truths in balanced pause (inner/decisive), Plurality holds a myriad truths simultaneously (outer/abundant). Spirit Seed through Air: deep knowing now containing multitudes. Number 9 is Abundance/Myriad — the outer face of the Spirit pair, where a single decisive insight has multiplied into the weight of many knowings. When this appears as a transient, the mind holds more than it can easily bear — not from confusion but from the sheer abundance of what's been perceived." },
  41: { name: "Clarity", traditional: "10 of Swords", channel: "Cognition", number: 10, archetype: 19,
       house: "Gestalt", function: "Fruition", horizon: "outer", wheelWorld: "Wheel", scale: "completive",
       numberKeyword: "Completion/Finality", numberHouse: "Gestalt",
       description: "Completion of cognition. Full seeing, nothing hidden.",
       extended: "Actualization (19) expressed through Air at the completion of the cycle. Same parent as Perception (32) but at the outer face: where Perception was the first cut of clarity (inner/beginning), Clarity is the final cut — nothing hidden, nothing left to see (outer/completion). Gestalt Fruition through Air: the whole self's radiant expression fully realized through understanding. Number 10 is Completion/Finality — the outer face of the Gestalt pair, the widest span complete. When this appears as a transient, a process of understanding has reached its natural end; the seeing is total." },

  // === RESONANCE CHANNEL (Water/Cups) ===
  // Resonance bounds express their parent archetype through emotional attunement and connection
  42: { name: "Receptivity", traditional: "Ace of Cups", channel: "Resonance", number: 1, archetype: 20,
       house: "Gestalt", function: "Feedback", horizon: "inner", wheelWorld: "World", scale: "formative",
       numberKeyword: "Beginning/Perfection", numberHouse: "Gestalt",
       description: "Beginning of felt awareness. Heart open, ready to receive.",
       extended: "Recognition (20) expressed through Water at the threshold of emergence. The Judgement archetype's integrative seeing meets the Resonance channel's demand for emotional attunement and produces the opening of feeling — the cup offered before anything has been poured. Number 1 is Beginning/Perfection — the inner face of the Gestalt pair, the pristine moment before emotional experience begins. This is felt awareness at its most nascent: the capacity to feel before there's anything specific to feel about. When this appears as a transient, the heart is opening to something new; readiness without attachment." },
  43: { name: "Merge", traditional: "2 of Cups", channel: "Resonance", number: 2, archetype: 18,
       house: "Spirit", function: "Feedback", horizon: "inner", wheelWorld: "World", scale: "formative",
       numberKeyword: "Balanced/Decisive", numberHouse: "Spirit",
       description: "Decisive connection through vision. Two becoming one flow.",
       extended: "Imagination (18) expressed through Water at the formative scale. The Moon archetype's capacity to navigate ambiguity meets Resonance and produces decisive emotional connection — two streams meeting and choosing to flow together. Spirit Feedback through Water: the integration of deep imaginative knowing through feeling. Number 2 is Balanced/Decisive — the inner face of the Spirit pair, where connection is a clear choice, not yet the abundance of many connections. This is the decisive moment of emotional meeting: two cups, one flow. When this appears as a transient, a genuine connection is being chosen." },
  44: { name: "Celebration", traditional: "3 of Cups", channel: "Resonance", number: 3, archetype: 5,
       house: "Mind", function: "Bridge", horizon: "inner", wheelWorld: "World", scale: "formative",
       numberKeyword: "Primal/Expansive", numberHouse: "Mind",
       description: "Primal joy through shared meaning. Community in celebration.",
       extended: "Culture (5) expressed through Water at the formative scale. The Hierophant archetype's transmission of shared meaning meets Resonance and produces communal joy — feeling that expands outward into shared celebration. Mind Bridge through Water: the sustained transmission of cultural meaning through emotional experience. Number 3 is Primal/Expansive — the inner face of the Mind pair, where shared feeling radiates outward before it deepens. Three cups raised together — community feeling at its most immediate and expansive. When this appears as a transient, joy wants to be shared; meaning is found in celebrating together." },
  45: { name: "Reverie", traditional: "4 of Cups", channel: "Resonance", number: 4, archetype: 6,
       house: "Emotion", function: "Seed", horizon: "inner", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "Peace/Stillness", numberHouse: "Emotion",
       description: "Peaceful connection, stable feeling. Sitting with what the heart knows.",
       extended: "Compassion (6) expressed through Water at the operative scale. The Lovers archetype's relational connection meets Resonance and produces reverie — feeling that has settled into its own depth, stable and contemplative. Emotion Seed through Water: the first stirring of relational consciousness expressed as feeling. Number 4 is Peace/Stillness — the inner face of the Emotion pair, where feeling rests before it needs to choose among possibilities. The figure sitting with three cups, a fourth offered — the emotional world at rest, not yet stirred to action. When this appears as a transient, there's a need to sit with what the heart knows before moving." },
  46: { name: "Conscience", traditional: "5 of Cups", channel: "Resonance", number: 5, archetype: 11,
       house: "Body", function: "Fruition", horizon: "inner", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "Internal/Personal", numberHouse: "Body",
       description: "Internal felt-sense of fairness. The private moral compass that knows what's right.",
       extended: "Equity (11) expressed through Water at the operative scale. The Justice archetype's fair calibration meets Resonance and produces conscience — the private, felt knowing of what's right and what's owed. Body Fruition through Water: the harvest of embodied practice expressed through feeling. Number 5 is Internal/Personal — the inner face of the Body pair, where the moral accounting is private and personal. The three spilled cups before the two standing — loss measured internally, not publicly mourned. When this appears as a transient, the inner moral compass is active, weighing what feels fair against what is." },
  47: { name: "Reciprocity", traditional: "6 of Cups", channel: "Resonance", number: 6, archetype: 11,
       house: "Body", function: "Fruition", horizon: "outer", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "External/Shared", numberHouse: "Body",
       description: "External fair exchange. Giving and receiving in balance.",
       extended: "Equity (11) expressed through Water at the operative scale. Same parent as Conscience (46) but at the outer face: where Conscience processes fairness privately (inner/practical), Reciprocity expresses it through exchange with others (outer/group). Body Fruition through Water: the harvest of embodied justice now flowing between people. Number 6 is External/Shared — the outer face of the Body pair, where private emotional accounting becomes shared giving and receiving. When this appears as a transient, fairness is being expressed through generosity, sharing, or the restoration of emotional balance between people." },
  48: { name: "Allure", traditional: "7 of Cups", channel: "Resonance", number: 7, archetype: 6,
       house: "Emotion", function: "Seed", horizon: "outer", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "Gathering/Reaping", numberHouse: "Emotion",
       description: "Gathering emotional possibilities. The pull of what might be felt.",
       extended: "Compassion (6) expressed through Water at the operative scale. Same parent as Reverie (45) but at the outer face: where Reverie rests in stable feeling (inner/peaceful), Allure gathers all the possible feelings into a cloud of choice (outer/gathering). Emotion Seed through Water: the first stirring of relational consciousness now multiplied into many possibilities. Number 7 is Gathering/Reaping — the outer face of the Emotion pair, where feeling has expanded into the intoxicating abundance of emotional possibility. Seven cups offering visions — not confusion but the harvest of everything the heart might want. When this appears as a transient, many emotional possibilities are presenting themselves and the heart must choose." },
  49: { name: "Passage", traditional: "8 of Cups", channel: "Resonance", number: 8, archetype: 5,
       house: "Mind", function: "Bridge", horizon: "outer", wheelWorld: "World", scale: "completive",
       numberKeyword: "Unfathomable/Deep", numberHouse: "Mind",
       description: "Deep threshold of shared meaning. Walking toward what connects.",
       extended: "Culture (5) expressed through Water at the completive scale. Same parent as Celebration (44) but at the outer face: where Celebration radiates shared joy outward (inner/expansive), Passage goes deep into what shared meaning actually requires — leaving what no longer serves connection (outer/profound). Mind Bridge through Water: the sustained transmission of cultural meaning now at its threshold. Number 8 is Unfathomable/Deep — the outer face of the Mind pair, where emotional depth has reached the point of necessary departure. Walking away from eight cups — not abandonment but the profound recognition that deeper connection lies elsewhere. When this appears as a transient, a threshold of emotional meaning has been reached." },
  50: { name: "Fulfillment", traditional: "9 of Cups", channel: "Resonance", number: 9, archetype: 18,
       house: "Spirit", function: "Feedback", horizon: "outer", wheelWorld: "World", scale: "completive",
       numberKeyword: "Abundance/Myriad", numberHouse: "Spirit",
       description: "Abundant vision realized. Deep satisfaction in what was imagined.",
       extended: "Imagination (18) expressed through Water at the completive scale. Same parent as Merge (43) but at the outer face: where Merge chose one decisive connection (inner/decisive), Fulfillment arrives at the abundant satisfaction of having fully imagined and fully felt (outer/abundant). Spirit Feedback through Water: the integration of imaginative knowing through the fullness of emotional experience. Number 9 is Abundance/Myriad — the outer face of the Spirit pair, where a single decisive choice has multiplied into deep contentment. The figure with nine cups — satisfied not because everything is perfect but because what was imagined has been felt. When this appears as a transient, deep emotional satisfaction is available." },
  51: { name: "Completion", traditional: "10 of Cups", channel: "Resonance", number: 10, archetype: 20,
       house: "Gestalt", function: "Feedback", horizon: "outer", wheelWorld: "World", scale: "completive",
       numberKeyword: "Completion/Finality", numberHouse: "Gestalt",
       description: "Emotional wholeness achieved. Full awareness of felt connection.",
       extended: "Recognition (20) expressed through Water at the completion of the cycle. Same parent as Receptivity (42) but at the outer face: where Receptivity opened to feeling (inner/beginning), Completion is the full rainbow of emotional awareness achieved (outer/completion). Gestalt Feedback through Water: the whole self's integrative seeing fully expressed through felt connection. Number 10 is Completion/Finality — the outer face of the Gestalt pair, the widest span complete. The ten cups forming a rainbow — not a single feeling but the entire spectrum of emotional awareness realized. When this appears as a transient, an emotional cycle has reached its natural wholeness." },

  // === STRUCTURE CHANNEL (Earth/Pentacles) ===
  // Structure bounds express their parent archetype through material form and manifestation
  52: { name: "Definition", traditional: "Ace of Pentacles", channel: "Structure", number: 1, archetype: 1,
       house: "Gestalt", function: "Bridge", horizon: "inner", wheelWorld: "World", scale: "formative",
       numberKeyword: "Beginning/Perfection", numberHouse: "Gestalt",
       description: "Beginning of directed form. The seed of what will be built.",
       extended: "Will (1) expressed through Earth at the threshold of emergence. The Magician archetype's directed agency meets the Structure channel's demand for material form and produces the seed of what will be built — the coin held in the hand, the resource that hasn't yet been invested. Number 1 is Beginning/Perfection — the inner face of the Gestalt pair, the Ace's pristine potential. Will through Earth: intentional creation at its most nascent, the first commitment of agency to form. When this appears as a transient, something concrete is ready to begin; a resource, an opportunity, or a material commitment is presenting itself." },
  53: { name: "Stewardship", traditional: "2 of Pentacles", channel: "Structure", number: 2, archetype: 3,
       house: "Spirit", function: "Bridge", horizon: "inner", wheelWorld: "World", scale: "formative",
       numberKeyword: "Balanced/Decisive", numberHouse: "Spirit",
       description: "Decisive cultivation through form. Tending what grows with responsible care.",
       extended: "Nurturing (3) expressed through Earth at the formative scale. The Empress archetype's care for growth meets Structure and produces stewardship — the responsible tending of material resources. Spirit Bridge through Earth: the sustained transmission of nurturing wisdom through practical form. Number 2 is Balanced/Decisive — the inner face of the Spirit pair, where competing demands must be held in dynamic balance through careful tending rather than force. The juggler with two coins — not choosing between priorities but stewarding both with grace. When this appears as a transient, material resources need responsible tending; the question is care, not control." },
  54: { name: "Formation", traditional: "3 of Pentacles", channel: "Structure", number: 3, archetype: 16,
       house: "Mind", function: "Feedback", horizon: "inner", wheelWorld: "World", scale: "formative",
       numberKeyword: "Primal/Expansive", numberHouse: "Mind",
       description: "Primal structure emerging. Skilled work building something new.",
       extended: "Breakthrough (16) expressed through Earth at the formative scale. The Tower archetype's sudden clearing of false structure meets Structure and produces formation — the skilled building of something genuinely new from what the clearing revealed. Mind Feedback through Earth: the integration of structural insight through material practice. Number 3 is Primal/Expansive — the inner face of the Mind pair, where new structure broadcasts outward in its first form. Three artisans building in the cathedral — Breakthrough's liberating force channeled into collaborative construction. When this appears as a transient, something is being built that couldn't exist before old structures were cleared." },
  55: { name: "Preservation", traditional: "4 of Pentacles", channel: "Structure", number: 4, archetype: 13,
       house: "Emotion", function: "Fruition", horizon: "inner", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "Peace/Stillness", numberHouse: "Emotion",
       description: "Peaceful stability through form. Holding what transformation produced.",
       extended: "Change (13) expressed through Earth at the operative scale. The Death archetype's necessary endings meet Structure and produce preservation — the stable holding of what transformation produced. Emotion Fruition through Earth: the harvest of emotional transformation expressed as material form. Number 4 is Peace/Stillness — the inner face of the Emotion pair, where change has settled into something worth holding. The figure holding four coins — not hoarding but preserving what the clearing created. When this appears as a transient, something produced by change needs to be held, stabilized, and protected before it's ready to be shared." },
  56: { name: "Steadfastness", traditional: "5 of Pentacles", channel: "Structure", number: 5, archetype: 8,
       house: "Body", function: "Seed", horizon: "inner", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "Internal/Personal", numberHouse: "Body",
       description: "Internal practical strength. Persisting through material pressure.",
       extended: "Fortitude (8) expressed through Earth at the operative scale. The Strength archetype's endurance meets Structure and produces steadfastness — the capacity to persist through material hardship by drawing on internal resources. Body Seed through Earth: the first stirring of embodied strength expressed as material endurance. Number 5 is Internal/Personal — the inner face of the Body pair, where the testing is private and the resources are one's own. Figures walking through snow past the lighted window — strength found in what you carry, not what you're given. When this appears as a transient, material difficulty is testing inner strength; the question is whether you can hold." },
  57: { name: "Support", traditional: "6 of Pentacles", channel: "Structure", number: 6, archetype: 8,
       house: "Body", function: "Seed", horizon: "outer", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "External/Shared", numberHouse: "Body",
       description: "External strength shared. Resources flowing where needed.",
       extended: "Fortitude (8) expressed through Earth at the operative scale. Same parent as Steadfastness (56) but at the outer face: where Steadfastness draws on internal resources privately (inner/practical), Support channels that strength outward to others (outer/group). Body Seed through Earth: embodied strength now flowing between people. Number 6 is External/Shared — the outer face of the Body pair, where private endurance becomes shared support. The figure with scales distributing coins — Fortitude's holding power transformed into material generosity. When this appears as a transient, resources need to flow toward those who need them; strength is being shared." },
  58: { name: "Harvest", traditional: "7 of Pentacles", channel: "Structure", number: 7, archetype: 13,
       house: "Emotion", function: "Fruition", horizon: "outer", wheelWorld: "Wheel", scale: "operative",
       numberKeyword: "Gathering/Reaping", numberHouse: "Emotion",
       description: "Gathering what transformation grew. Patient waiting rewarded.",
       extended: "Change (13) expressed through Earth at the operative scale. Same parent as Preservation (55) but at the outer face: where Preservation stabilizes what change produced (inner/peaceful), Harvest gathers and evaluates the material yield of transformation (outer/gathering). Emotion Fruition through Earth: the harvest of emotional transformation expressed as material result. Number 7 is Gathering/Reaping — the outer face of the Emotion pair, where patient transformation finally shows what it's produced. The farmer surveying growing plants — not the quiet holding but the active assessment of what the change has yielded. When this appears as a transient, it's time to evaluate what your patience and transformation have actually produced." },
  59: { name: "Commitment", traditional: "8 of Pentacles", channel: "Structure", number: 8, archetype: 16,
       house: "Mind", function: "Feedback", horizon: "outer", wheelWorld: "World", scale: "completive",
       numberKeyword: "Unfathomable/Deep", numberHouse: "Mind",
       description: "Deep threshold of new structure. Dedicated craft, persistent building.",
       extended: "Breakthrough (16) expressed through Earth at the completive scale. Same parent as Formation (54) but at the outer face: where Formation builds the first new structure (inner/expansive), Commitment deepens into the profound mastery that only sustained craft produces (outer/profound). Mind Feedback through Earth: the integration of structural insight through relentless material practice. Number 8 is Unfathomable/Deep — the outer face of the Mind pair, where building has reached the threshold of genuine mastery. The artisan with eight coins — each one deeper, more refined than the last. Breakthrough's liberating force channeled into the depth of dedicated craft. When this appears as a transient, dedicated practice is reaching a threshold of real skill." },
  60: { name: "Flourishing", traditional: "9 of Pentacles", channel: "Structure", number: 9, archetype: 3,
       house: "Spirit", function: "Bridge", horizon: "outer", wheelWorld: "World", scale: "completive",
       numberKeyword: "Abundance/Myriad", numberHouse: "Spirit",
       description: "Abundant growth achieved. Enjoying what careful tending produced.",
       extended: "Nurturing (3) expressed through Earth at the completive scale. Same parent as Flow (53) but at the outer face: where Flow balances competing demands with grace (inner/decisive), Flourishing arrives at the abundant result of sustained tending (outer/abundant). Spirit Bridge through Earth: the sustained transmission of nurturing wisdom now visible in material abundance. Number 9 is Abundance/Myriad — the outer face of the Spirit pair, where careful cultivation has multiplied into rich harvest. The figure in the garden with nine coins — Nurturing's patient care expressed as material flourishing. When this appears as a transient, what you've tended is bearing abundant fruit." },
  61: { name: "Achievement", traditional: "10 of Pentacles", channel: "Structure", number: 10, archetype: 1,
       house: "Gestalt", function: "Bridge", horizon: "outer", wheelWorld: "World", scale: "completive",
       numberKeyword: "Completion/Finality", numberHouse: "Gestalt",
       description: "Completion of directed form. Legacy established through sustained will.",
       extended: "Will (1) expressed through Earth at the completion of the cycle. Same parent as Definition (52) but at the outer face: where Initiation was the seed of what would be built (inner/beginning), Achievement is the legacy fully established (outer/completion). Gestalt Bridge through Earth: the whole self's directed agency fully materialized through sustained effort. Number 10 is Completion/Finality — the outer face of the Gestalt pair, the widest span complete. The ten coins forming the Tree of Life pattern — Will's capacity to direct attention has produced lasting material form. When this appears as a transient, a material cycle has reached its natural completion; what was willed into being now stands." }
};

export const AGENTS = {
  // === INTENT CHANNEL (Fire/Wands) AGENTS ===
  // Intent agents: parent archetype's behavioral expression through directed will
  // Agent horizon = parent archetype's creation/operation phase (0-9=inner, 11-20=outer)
  62: { name: "Initiate of Intent", traditional: "Page of Wands", channel: "Intent", role: "Initiate", archetype: 17,
       house: "Spirit", function: "Fruition", horizon: "outer", wheelWorld: "Wheel",
       domain: "Spirit", nickname: "The Spark", boundNumbers: [2, 9],
       description: "Inspiration-as-behavior: radiant confidence, authentic self-expression.",
       extended: "Inspiration (17) showing up as observable behavior through the Intent channel. The Spark — fresh enthusiasm for direction, the fire before it knows where it's going. As Initiate, this is learning energy: exploring, aspiring, asking. The Star archetype doesn't just aspire in the abstract here — it lights fires, starts things, radiates confidence that pulls others along. Spirit domain through Fire: inner knowing expressed as outward spark. Outer horizon (operation phase parent) — this is Inspiration already matured, now discovering how to act on its vision. Bounds: Orientation (2W, inner) and Resilience (9W, outer) define the operational range of this behavior." },
  63: { name: "Catalyst of Intent", traditional: "Knight of Wands", channel: "Intent", role: "Catalyst", archetype: 4,
       house: "Mind", function: "Seed", horizon: "inner", wheelWorld: "Wheel",
       domain: "Mind", nickname: "The Warrior", boundNumbers: [3, 8],
       description: "Order-as-behavior: decisive leadership, boundary-setting, charging forward.",
       extended: "Order (4) showing up as observable behavior through the Intent channel. The Warrior — moving, transforming, cutting through inertia with decisive action. As Catalyst, this is activating energy: creating change through momentum. The Emperor archetype doesn't just organize here — it charges, leads from the front, sets boundaries by crossing them. Mind domain through Fire: structural pattern expressed as forceful action. Inner horizon (creation phase parent) — this is Order still forming, discovering its power through motion. Bounds: Assertion (3W, inner) and Command (8W, outer) define the operational range of this behavior." },
  64: { name: "Steward of Intent", traditional: "Queen of Wands", channel: "Intent", role: "Steward", archetype: 7,
       house: "Emotion", function: "Bridge", horizon: "inner", wheelWorld: "World",
       domain: "Emotion", nickname: "The Inspirer", boundNumbers: [4, 7],
       description: "Drive-as-behavior: sustained motivation, courage, tending the fire without burning out.",
       extended: "Drive (7) showing up as observable behavior through the Intent channel. The Inspirer — holding, maintaining, relating with warmth and sustained motivation. As Steward, this is nurturing energy: creating conditions for directed action to flourish. The Chariot archetype doesn't just charge here — it holds space for momentum, tends the fire, inspires others to keep going. Emotion domain through Fire: emotional drive expressed as sustained motivational presence. Inner horizon (creation phase parent) — this is Drive still in its formative phase, nurturing direction with care rather than force. Bounds: Alignment (4W, inner) and Resolve (7W, outer) define the operational range of this behavior." },
  65: { name: "Executor of Intent", traditional: "King of Wands", channel: "Intent", role: "Executor", archetype: 12,
       house: "Body", function: "Feedback", horizon: "outer", wheelWorld: "World",
       domain: "Body", nickname: "The Commander", boundNumbers: [5, 6],
       description: "Sacrifice-as-behavior: surrender, duty-bearing, knowing when to release as well as push.",
       extended: "Sacrifice (12) showing up as observable behavior through the Intent channel. The Commander — completing, embodying, governing with the authority that comes from knowing what to let go of. As Executor, this is mastery energy: directing the fire with full knowledge of its cost. The Hanged Man archetype doesn't just release here — it commands through the wisdom of release, governing with authority earned by sacrifice. Body domain through Fire: embodied surrender expressed as masterful direction. Outer horizon (operation phase parent) — this is Sacrifice fully operational, applying its wisdom of release with authority. Bounds: Dedication (5W, inner) and Recognition (6W, outer) define the operational range — the tightest span (Body pair), the most concrete expression." },

  // === COGNITION CHANNEL (Air/Swords) AGENTS ===
  // Cognition agents: parent archetype's behavioral expression through mental clarity
  66: { name: "Initiate of Cognition", traditional: "Page of Swords", channel: "Cognition", role: "Initiate", archetype: 2,
       house: "Spirit", function: "Seed", horizon: "inner", wheelWorld: "Wheel",
       domain: "Spirit", nickname: "The Student", boundNumbers: [2, 9],
       description: "Wisdom-as-behavior: listening, discerning, perceiving with fresh curiosity.",
       extended: "Wisdom (2) showing up as observable behavior through the Cognition channel. The Student — learning, exploring, aspiring to understand. Fresh curiosity, eager to grasp what the deeper mind already knows. The High Priestess archetype doesn't just know here — she inquires, questions, turns over every stone with the energy of discovery. Spirit domain through Air: inner knowing expressed as mental exploration. Inner horizon (creation phase parent) — this is Wisdom still forming, discovering its capacity through questions rather than answers. Bounds: Reflection (2S, inner) and Plurality (9S, outer) define the operational range of this behavior." },
  67: { name: "Catalyst of Cognition", traditional: "Knight of Swords", channel: "Cognition", role: "Catalyst", archetype: 15,
       house: "Mind", function: "Fruition", horizon: "outer", wheelWorld: "Wheel",
       domain: "Mind", nickname: "The Strategist", boundNumbers: [3, 8],
       description: "Abstraction-as-behavior: strategic reasoning, cutting through to pure logic.",
       extended: "Abstraction (15) showing up as observable behavior through the Cognition channel. The Strategist — moving, transforming understanding through the speed and precision of pure thought. Thought in rapid motion, cutting through to truth. The Devil archetype (freed pattern) doesn't just recognize here — it charges forward with strategic reasoning, dismantling illusions through intellectual force. Mind domain through Air: pure pattern expressed as mental catalyst. Outer horizon (operation phase parent) — this is Abstraction fully operational, its pattern-recognition deployed at speed. Bounds: Calculation (3S, inner) and Immersion (8S, outer) define the operational range of this behavior." },
  68: { name: "Steward of Cognition", traditional: "Queen of Swords", channel: "Cognition", role: "Steward", archetype: 14,
       house: "Emotion", function: "Feedback", horizon: "outer", wheelWorld: "World",
       domain: "Emotion", nickname: "The Analyst", boundNumbers: [4, 7],
       description: "Tune-as-behavior: calibration, truth-telling tempered with discernment.",
       extended: "Tune (14) showing up as observable behavior through the Cognition channel. The Analyst — holding, maintaining clarity with care and mature discernment. Truth-telling tempered with the wisdom of when and how to speak. The Temperance archetype doesn't just calibrate here — she holds the space for clear perception, relating to others through precise and compassionate thought. Emotion domain through Air: dynamic equilibrium expressed as analytical presence. Outer horizon (operation phase parent) — this is Balance fully operational, its calibrating wisdom applied with mature authority. Bounds: Repose (4S, inner) and Reconciliation (7S, outer) define the operational range of this behavior." },
  69: { name: "Executor of Cognition", traditional: "King of Swords", channel: "Cognition", role: "Executor", archetype: 9,
       house: "Body", function: "Bridge", horizon: "inner", wheelWorld: "World",
       domain: "Body", nickname: "The Judge", boundNumbers: [5, 6],
       description: "Discipline-as-behavior: rigorous inquiry, method, embodied clarity.",
       extended: "Discipline (9) showing up as observable behavior through the Cognition channel. The Judge — completing, embodying, governing through rigorous and disciplined clarity. Authority from sustained mental practice, not inspiration. The Hermit archetype doesn't just practice here — he rules through method, deciding with the precision of someone who has done the work. Body domain through Air: focused practice expressed as intellectual mastery. Inner horizon (creation phase parent) — this is Discipline still in its formative depth, governing from the solitary lamp of sustained attention. Bounds: Discernment (5S, inner) and Guidance (6S, outer) define the operational range — the tightest span, the most concrete expression of mental authority." },

  // === RESONANCE CHANNEL (Water/Cups) AGENTS ===
  // Resonance agents: parent archetype's behavioral expression through emotional attunement
  70: { name: "Initiate of Resonance", traditional: "Page of Cups", channel: "Resonance", role: "Initiate", archetype: 18,
       house: "Spirit", function: "Feedback", horizon: "outer", wheelWorld: "World",
       domain: "Spirit", nickname: "The Dreamer", boundNumbers: [2, 9],
       description: "Imagination-as-behavior: sensing, envisioning, navigating ambiguity with fresh wonder.",
       extended: "Imagination (18) showing up as observable behavior through the Resonance channel. The Dreamer — learning, exploring emotional depths with fresh sensitivity and wonder. The heart discovering its capacity to feel what hasn't happened yet. The Moon archetype doesn't just navigate ambiguity here — she opens to it with the wide-eyed trust of someone encountering the depth of feeling for the first time. Spirit domain through Water: imaginative knowing expressed as emotional exploration. Outer horizon (operation phase parent) — this is Imagination fully operational but approaching feeling with beginner's eyes. Bounds: Merge (2C, inner) and Fulfillment (9C, outer) define the operational range of this behavior." },
  71: { name: "Catalyst of Resonance", traditional: "Knight of Cups", channel: "Resonance", role: "Catalyst", archetype: 5,
       house: "Mind", function: "Bridge", horizon: "inner", wheelWorld: "World",
       domain: "Mind", nickname: "The Romantic", boundNumbers: [3, 8],
       description: "Culture-as-behavior: teaching, ritualizing, pursuing emotional truth through meaning.",
       extended: "Culture (5) showing up as observable behavior through the Resonance channel. The Romantic — moving, transforming through the passionate pursuit of emotional truth and shared meaning. Feeling in motion, the knight who quests for connection. The Hierophant archetype doesn't just transmit here — he charges toward what connects, creating change through emotional intensity and the pursuit of meaningful relationship. Mind domain through Water: shared meaning expressed as emotional catalyst. Inner horizon (creation phase parent) — this is Culture still forming, discovering its capacity through romantic pursuit rather than established tradition. Bounds: Celebration (3C, inner) and Passage (8C, outer) define the operational range of this behavior." },
  72: { name: "Steward of Resonance", traditional: "Queen of Cups", channel: "Resonance", role: "Steward", archetype: 6,
       house: "Emotion", function: "Seed", horizon: "inner", wheelWorld: "Wheel",
       domain: "Emotion", nickname: "The Empath", boundNumbers: [4, 7],
       description: "Compassion-as-behavior: relational coherence, empathy, holding space for feeling.",
       extended: "Compassion (6) showing up as observable behavior through the Resonance channel. The Empath — holding, maintaining, relating with deep emotional attunement and compassionate presence. Holding space for others' feeling without drowning in it. The Lovers archetype doesn't just connect here — she tends connection, nurtures the space between people where real relating happens. Emotion domain through Water: relational alignment expressed as emotional stewardship. Inner horizon (creation phase parent) — this is Compassion still in its formative depth, nurturing connection from the heart's own fullness. Bounds: Reverie (4C, inner) and Allure (7C, outer) define the operational range of this behavior." },
  73: { name: "Executor of Resonance", traditional: "King of Cups", channel: "Resonance", role: "Executor", archetype: 11,
       house: "Body", function: "Fruition", horizon: "outer", wheelWorld: "Wheel",
       domain: "Body", nickname: "The Healer", boundNumbers: [5, 6],
       description: "Equity-as-behavior: fair emotional judgment, principled governance of feeling.",
       extended: "Equity (11) showing up as observable behavior through the Resonance channel. The Healer — completing, embodying, governing emotion with the authority of principled fairness. Feeling deeply while maintaining equanimity. The Justice archetype doesn't just calibrate here — she governs the emotional realm with earned authority, deciding with the precision of someone who has fully felt and emerged with balance. Body domain through Water: fair calibration expressed as emotional mastery. Outer horizon (operation phase parent) — this is Equity fully operational, its principled judgment applied to the realm of feeling. Bounds: Conscience (5C, inner) and Reciprocity (6C, outer) define the operational range — the tightest span, the most concrete emotional authority." },

  // === STRUCTURE CHANNEL (Earth/Pentacles) AGENTS ===
  // Structure agents: parent archetype's behavioral expression through material form
  74: { name: "Initiate of Structure", traditional: "Page of Pentacles", channel: "Structure", role: "Initiate", archetype: 3,
       house: "Spirit", function: "Bridge", horizon: "inner", wheelWorld: "World",
       domain: "Spirit", nickname: "The Apprentice", boundNumbers: [2, 9],
       description: "Nurturing-as-behavior: tending, growing, learning how material things flourish.",
       extended: "Nurturing (3) showing up as observable behavior through the Structure channel. The Apprentice — learning, exploring the material world with fresh engagement and care. Learning how things grow by tending them. The Empress archetype doesn't just nurture here — she apprentices herself to the material world, discovering through patient attention how form develops. Spirit domain through Earth: caring wisdom expressed as practical learning. Inner horizon (creation phase parent) — this is Nurturing still forming, discovering its capacity through hands-on engagement with material reality. Bounds: Stewardship (2P, inner) and Flourishing (9P, outer) define the operational range of this behavior." },
  75: { name: "Catalyst of Structure", traditional: "Knight of Pentacles", channel: "Structure", role: "Catalyst", archetype: 16,
       house: "Mind", function: "Feedback", horizon: "outer", wheelWorld: "World",
       domain: "Mind", nickname: "The Pioneer", boundNumbers: [3, 8],
       description: "Breakthrough-as-behavior: forcing structural change into reality, slow but unstoppable.",
       extended: "Breakthrough (16) showing up as observable behavior through the Structure channel. The Pioneer — moving, transforming material reality through steady, persistent effort. Slow but unstoppable. The Tower archetype doesn't just clear here — it pioneers, forcing structural change into physical form through relentless forward motion. Mind domain through Earth: structural liberation expressed as material catalyst. Outer horizon (operation phase parent) — this is Breakthrough fully operational, its clearing force channeled into the patient persistence of real-world building. Bounds: Formation (3P, inner) and Commitment (8P, outer) define the operational range of this behavior." },
  76: { name: "Steward of Structure", traditional: "Queen of Pentacles", channel: "Structure", role: "Steward", archetype: 13,
       house: "Emotion", function: "Fruition", horizon: "outer", wheelWorld: "Wheel",
       domain: "Emotion", nickname: "The Provider", boundNumbers: [4, 7],
       description: "Change-as-behavior: releasing, transforming, creating conditions for sustainable material growth.",
       extended: "Change (13) showing up as observable behavior through the Structure channel. The Provider — holding, maintaining material abundance by knowing what to release and what to keep. Creating conditions for sustainable growth through transformation. The Death archetype doesn't just end things here — she provides by composting the old into fertile ground for new material growth. Emotion domain through Earth: necessary transformation expressed as nurturing material stewardship. Outer horizon (operation phase parent) — this is Change fully operational, its transforming force applied with mature care to the material world. Bounds: Preservation (4P, inner) and Harvest (7P, outer) define the operational range of this behavior." },
  77: { name: "Executor of Structure", traditional: "King of Pentacles", channel: "Structure", role: "Executor", archetype: 8,
       house: "Body", function: "Seed", horizon: "inner", wheelWorld: "Wheel",
       domain: "Body", nickname: "The Builder", boundNumbers: [5, 6],
       description: "Fortitude-as-behavior: embodied strength, stabilizing power, building that endures.",
       extended: "Fortitude (8) showing up as observable behavior through the Structure channel. The Builder — completing, embodying, governing the material realm with the authority of someone who has built and held and endured. Building that lasts through generations. The Strength archetype doesn't just endure here — she governs through embodied power, deciding what to build with the mastery of someone who knows what it costs. Body domain through Earth: resilient strength expressed as material mastery. Inner horizon (creation phase parent) — this is Fortitude still in its formative depth, governing from the bedrock of embodied practice. Bounds: Steadfastness (5P, inner) and Support (6P, outer) define the operational range — the tightest span, the most concrete material authority." }
};
