// Canonical derivation of the 16 toroidal neighborhoods.
// Source: D:\nirmanakaya_book\MASTER_CANON\canon\Neighborhoods_Canon.md (829 lines, derived 2026-04-16)
// Fields per neighborhood: definition, whyFour, collapseMeans, practical, healthy, shadow, adjacency, confidence, nameStatus.
// All 16 entries are status=Derived unless otherwise noted.

export const NEIGHBORHOOD_CANON = {
  'Luminous Direction': {
    definition: `Luminous Direction is the neighborhood where consciousness aims toward what it hasn't yet become. Aspiration (Inspiration, Wisdom) meets feeling (Drive, Balance) through the double Activity of fire and air — propulsion and discernment together. What results is a vector with a lamp on the front. The neighborhood IS the phenomenon of knowing where to go and moving toward it because you can see it. Not planning. Not wishing. Actual directional alignment between what you perceive, what you want, and what you are willing to burn in order to reach it.`,
    whyFour: `Creation at the mode of Directed Perception must solve two problems at once: where to aim and how to see clearly enough to aim well. Inspiration (radiant aspiration) and Drive (emotional momentum) supply the aim. Wisdom (direct perception) and Balance (integrative equanimity) supply the sight. Remove Wisdom and the vector becomes zeal without discernment. Remove Drive and the lamp burns with no one walking toward it. Remove Inspiration and there is nothing worth moving toward. Remove Balance and the heat of aiming consumes the aimer.`,
    collapseMeans: `Identity collapses. When you are genuinely in this neighborhood, who you are is not in question — only where you are going is. Identity-work takes a back seat because aspiration has organized the self around a clear vector. The person aimed toward true north is not confused about who they are; they are busy aiming.`,
    practical: `The moment a decision clarifies. Someone who has been circling a career change, a relationship, or a creative project suddenly sees the angle, feels the pull, and names it cleanly — with warmth, not with grit. A project that's been fogged takes a heading. Watch for: clarity that arrives without strain; the feeling of "yes, that's the one"; vision that survives a night's sleep.`,
    healthy: `Direction arises from integrated perception; the aim is clear, the feeling is warm, the seer and the walker are the same person. Others experience it as a tonic.`,
    shadow: `The lamp goes ahead of the walker — ungrounded radiance (Inspiration overextended) seduces Drive into chasing what Wisdom hasn't verified and Balance can't sustain. The aim becomes a fantasy that burns the aimer. Or inversely: Balance over-moderates, Drive is damped, and Wisdom's caution silences Inspiration — the vector never fires.`,
    adjacency: `Across Practice-pair: Open Reception softens aim into attunement; Fertile Transform grounds aim into composting; Generative Force concretizes aim into making. Across Activity-pair: Commanded Power adds intensity and the question of authority; Price of Knowing adds structural cost and discipline; Sacred Witness adds body and the wisdom of not-doing.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Luminous" holds Wisdom\'s clarity and Inspiration\'s radiance; "Direction" holds Drive\'s momentum and the arc\'s aiming function.',
  },

  'Open Reception': {
    definition: `Open Reception is the neighborhood where consciousness takes in what it has not generated. Aspiration and feeling meet through the Activity-pair of air and water — discernment and connection together — producing a mode in which truth is recognized rather than constructed. Wisdom perceives. Balance integrates. Imagination dreams what the perception means. Compassion recognizes the other. Together they form the receiving pose of Creation — not passive, but actively available. The neighborhood IS the phenomenon of being changed by what you meet because you were willing to be met.`,
    whyFour: `Creation requires something to create with, which means consciousness must at some point receive. Reception at the mode of Relational Knowing is attunement — the cognition that occurs because contact has been made. Wisdom opens the threshold. Compassion recognizes the other across it. Balance holds the meeting in equilibrium. Imagination weaves what passes through into meaning. Remove Compassion and the reception becomes abstract. Remove Wisdom and it becomes impression without discernment. Remove Imagination and it fails to integrate. Remove Balance and the receiver tips over into merger.`,
    collapseMeans: `Stage collapses. The four-fold Stage distinction narrows to two — Seed and Feedback. Reception is an opening and a return; the Medium and Fruition of making are absent. When the neighborhood is active, you are not building or completing. You are receiving an impression and letting it reverberate. The stages of work disappear because the work is receptivity itself.`,
    practical: `The moment someone finally hears what has been said to them. A reader meets a text and the text changes them. A partner listens without rehearsing reply. A therapist receives a dream without interpreting it too early. Watch for: slowing, softening, the feeling of meeting without defending; perception that arrives as a gift rather than a capture; the capacity to be moved.`,
    healthy: `Reception preserves the receiver. Boundaries stay distinct while attunement deepens. The receiver leaves the encounter more themselves, not less.`,
    shadow: `Compassion overextends and Balance fails to hold center — reception becomes merger. Or the reverse: Wisdom over-guards, Balance rigidifies, and reception becomes the performance of listening without actual opening.`,
    adjacency: `Across Practice-pair: Luminous Direction sharpens reception into aim; Fertile Transform roots it in composting; Generative Force pushes it out as making. Across Activity-pair: Anatomy of Relation adds intensity and the dissection of what was received; Tested Truth adds structural testing; Silent Knowing adds body and time — reception that has matured into wordless knowing.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Open" captures the Seed-Feedback stage collapse (no middle, just arrival and return); "Reception" captures the relational-knowing-of-what-arrives character.',
  },

  'Fertile Transform': {
    definition: `Fertile Transform is the neighborhood where consciousness composts. Aspiration and feeling meet through water and earth — connection and form together — producing the mode in which what has ended becomes material for what will begin. Imagination dreams the new possibility. Compassion honors what is passing. Nurturing tends the compost. Change releases the old form. The neighborhood IS the phenomenon of transformation that happens in ground, not in theory — the decomposition that yields soil for the next growth. Creation in its middle passage: no longer pure aim, not yet new form.`,
    whyFour: `Creation at the mode of Grounded Holding must do the messy work of metabolism. Imagination and Compassion cooperate with Nurturing and Change to make the transformation ecological rather than violent. Without Nurturing, Change becomes destruction. Without Change, Nurturing becomes preservation without renewal. Without Imagination, the transformation has no forward vision. Without Compassion, it loses tenderness toward what is dying.`,
    collapseMeans: `Identity collapses. Who the transformer IS becomes less distinct as the members span the two Near-aligned Identity values. The work of transformation dissolves fixed self-position; one cannot compost the old self while clutching it. The collapse signals: this neighborhood asks you to loosen identity so transformation can happen through you rather than to you.`,
    practical: `The end-of-phase turning that precedes a new chapter. The last months of a marriage whose ending is already underway but whose grief is still tender. The slow dissolve of an old professional identity as a new one forms underneath. The hospice of a project that has served its purpose. Watch for: heaviness that is not depression but gestation; the strange sweetness of endings; the body's quiet knowledge that this is necessary.`,
    healthy: `Change and Nurturing cooperate — releasing is tender, tending is honest. Imagination holds the forward vision without rushing. Compassion keeps the work relational. The compost heap heats up and new soil is made.`,
    shadow: `Change overextends and the transformation becomes premature demolition — nothing has time to decompose. Or Nurturing overextends and the old form is preserved past its moment, rotting the ground it was meant to fertilize. Imagination without Compassion fantasizes the next chapter while the current one is still bleeding.`,
    adjacency: `Across Practice-pair: Luminous Direction sharpens compost into aim; Open Reception softens it into receiving; Generative Force pushes the new growth into the world. Across Activity-pair: Relational Crisis adds intensity — compost under pressure of breaking; Load-Bearing Truth adds structural weight; Gentle Stewardship adds wisdom — the experienced gardener's touch.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Fertile" holds the Nurturing-Imagination ground, "Transform" holds the Change-Compassion passage. Together they name composting as a verb-forward act.',
  },

  'Generative Force': {
    definition: `Generative Force is the neighborhood where consciousness makes. Aspiration and feeling meet through earth and fire — form and propulsion together — producing the mode in which the new is not merely imagined but pushed into being. Nurturing grows it. Change clears space for it. Inspiration aims the radiance. Drive provides the momentum. The neighborhood IS the phenomenon of creation as output — the moment when everything that was received, composted, and directed now emerges as something in the world. The hand on the chisel, the word typed, the child born.`,
    whyFour: `Creation at the mode of Creative Building is the terminal phase of the arc. Nurturing supplies the sustaining ground that keeps the making alive. Change supplies the release of what can no longer be held onto. Inspiration supplies the vector. Drive supplies the heat. Remove Drive and the making stalls. Remove Nurturing and the new thing is born without soil to grow in. Remove Inspiration and the force is mechanical. Remove Change and the making never clears enough space to begin.`,
    collapseMeans: `Stage collapses. The four-fold Stage distinction narrows to two — Medium and Fruition. The neighborhood skips the opening (Seed) and the return (Feedback); it is entirely in the middle and the completion of making. When this neighborhood is active, you are in the doing, and the doing is bringing something to its full form.`,
    practical: `The productive moments when all the earlier work pays out. Writing the draft that has been gestating for months. Shipping the product. Teaching the class that contains everything you've learned. A birth, literal or figurative. Watch for: momentum that feels earned rather than forced; the satisfaction of watching form appear under your hands; the strange quiet of actual work, distinct from the noise of preparation.`,
    healthy: `Drive burns from feeling that matters; Inspiration radiates what was genuinely cultivated; Nurturing keeps the making alive over time; Change lets go of what must go to make room. The output is honest and serves.`,
    shadow: `Drive runs unmoored from Inspiration — producing at volume without vision. Or Change overextends into demolition-as-productivity, mistaking destruction for generation. Or Nurturing strangles the making with over-tending. All four archetypes over-firing at once: frantic production.`,
    adjacency: `Across Practice-pair: Luminous Direction aims the making; Open Reception takes in what the making needs; Fertile Transform composts the making's leftovers. Across Activity-pair: Revolution adds political intensity — making that overthrows; Foundation adds structural sobriety — making that holds; Grace adds wisdom — making that does not grasp.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Generative" holds the creation-arc, "Force" holds the Drive+Change intensity of Creative Building. Together: creation as active force, not passive unfolding.',
  },

  'Commanded Power': {
    definition: `Commanded Power is the neighborhood where force is exercised through understanding. Feeling and thought meet through fire and air — propulsion and discernment together — producing the mode in which authority moves. Drive propels. Order structures. Balance moderates. Abstraction reveals the pattern underneath. The neighborhood IS the phenomenon of authority without tyranny — power that has been disciplined by thought and cooled by integration, aimed by intent and illuminated by seeing. The general who knows the terrain. The parent who knows the child. The leader whose decisions actually fit the situation.`,
    whyFour: `Intensity at the mode of Directed Perception requires force that is also perception. Drive carries the emotional heat that makes action possible. Order supplies the mental structure that organizes that heat. Balance keeps the commander from being consumed by their own commanding. Abstraction reveals the underlying patterns so commands correspond to structural reality, not fantasy. Remove Abstraction and the command ignores the real chains. Remove Balance and the commander loses themselves. Remove Order and the power becomes rage. Remove Drive and there is nothing to command with.`,
    collapseMeans: `Being collapses. What is happening in the neighborhood — what kind of occurrence it is — becomes less distinct because the character of command simultaneously holds multiple values. When authority is being exercised well, the occurrence-flavor ceases to be the question. The question is: does this command fit the terrain? Being recedes; fit becomes the criterion.`,
    practical: `Moments of justified exercise of authority. A judge handing down a sentence that actually serves. A surgeon making the right cut. A manager firing someone who had to be fired, kindly. A parent saying no when no is what love requires. Watch for: the quiet of well-exercised authority (unlike the loudness of unjustified power); decisions that land without flailing; the absence of self-congratulation.`,
    healthy: `The four members cooperate — feeling underwrites the decision, thought structures it, pattern-seeing grounds it, equanimity delivers it. The command is proportionate. Those commanded experience it as service.`,
    shadow: `Drive overextends and Order becomes rigidity — authoritarian tyranny. Or Abstraction dissociates and the commander commands from theory not terrain. Or Balance over-moderates and the command never lands. Or Drive collapses and the neighborhood produces paralysis dressed as prudence.`,
    adjacency: `Across Practice-pair: Luminous Direction softens command into direction; Price of Knowing sharpens it into sacrifice; Sacred Witness matures it into presence. Across Activity-pair: Anatomy of Relation moves power into dissection of connection; Relational Crisis moves it into the pressure-point; Revolution converts it into the making of new order.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Commanded" names the Order+Drive authority-structure; "Power" names the Intensity arc\'s central phenomenon.',
  },

  'Anatomy of Relation': {
    definition: `Anatomy of Relation is the neighborhood where connection is placed under the lens. Feeling and thought meet through air and water — discernment and connection together — producing the mode in which relationship itself becomes the object of understanding. Balance centers the observer. Abstraction reveals structural pattern. Compassion maintains contact. Culture supplies the shared vocabulary. The neighborhood IS the phenomenon of understanding what relationship actually is by being in one while thinking about it — therapy, dialogue, the hard conversation, the moment a couple sees the shape of their dynamic for the first time.`,
    whyFour: `Intensity at the mode of Relational Knowing generates the pressure of seeing what has been happening between people. Compassion supplies the felt connection without which dissection becomes cold. Abstraction supplies the capacity to see pattern. Culture supplies the language that makes the seeing shareable. Balance keeps the dissecting observer from becoming the disembodied analyst. Remove Compassion and the anatomy becomes clinical — the relationship dies on the table.`,
    collapseMeans: `Identity collapses. Who each party is becomes less fixed as the relationship itself is examined. The work of the neighborhood dissolves fixed positions so the dynamic between them becomes visible. The question "who am I?" gives way to "what is this we are doing together?" — and identity softens to make the second question askable.`,
    practical: `The conversation where both parties finally see the pattern. A couple in therapy naming the dance they've been in. Two colleagues realizing why their collaboration keeps stalling. A parent and adult child understanding their transference. Watch for: the shift from blame to pattern-naming; the moment pronouns change from "you" to "we"; the strange intimacy of being dissected together with someone.`,
    healthy: `Compassion and Abstraction cooperate — love does not block sight and sight does not kill love. The relationship survives being looked at. Culture provides the words and Balance keeps the looker in their body.`,
    shadow: `Abstraction overextends into clinical distance — the dissection kills the thing. Or Compassion overextends and the anatomy never resolves — endless sympathetic discussion that changes nothing. Or Culture imposes vocabulary that flattens the specific. Or Balance dissociates into false neutrality.`,
    adjacency: `Across Practice-pair: Open Reception softens anatomy into attunement; Tested Truth shifts it to structural validation; Silent Knowing matures it beyond the need for words. Across Activity-pair: Commanded Power moves the heat into aimed authority; Relational Crisis moves it into the pressure point; Revolution converts it into overthrow.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Anatomy" captures the Abstraction+Balance dissective precision; "Relation" captures the Compassion+Culture connective substrate.',
  },

  'Relational Crisis': {
    definition: `Relational Crisis is the neighborhood where connection meets structural reality and one of them must give. Feeling and thought meet through water and earth — connection and form together — producing the mode in which a relationship or shared meaning reaches the point where continuing in its current form is impossible. Compassion still loves. Culture still holds the form. Change releases. Breakthrough shatters. The neighborhood IS the phenomenon of the pressure-point that forces evolution — the marriage that must change or end, the community whose tradition can no longer hold its members, the institution that must reform or fall.`,
    whyFour: `Intensity at the mode of Grounded Holding is the phase where heat meets material. The relationship has substance (Culture), connection (Compassion), and has reached the point where form must move (Change) or shatter (Breakthrough). Remove Compassion and the crisis becomes mere structural collapse. Remove Culture and there is no shared form to test. Remove Change and the pressure has no release route. Remove Breakthrough and the form cannot fail cleanly.`,
    collapseMeans: `Being collapses. What is happening becomes ambiguous, multi-valent, too large to name. Crisis is the state where you cannot easily say what is occurring because several occurrences are superimposed — grief, love, anger, relief, fear — all at once. Being collapses because the character of the moment cannot be pinned to a single register.`,
    practical: `The crises that every bonded unit eventually faces. The fight that either ends the relationship or deepens it. The community's reckoning with the founder's failures. The generational break when the old forms no longer reach the young. Watch for: high intensity combined with structural weight; the sense that the form itself is under test; grief and rage running together; the knowledge that pretending this is not happening will cost more than facing it.`,
    healthy: `Compassion keeps the crisis relational. Culture provides ritual and language for passage. Change releases what must go. Breakthrough shatters cleanly what cannot be reformed. The result is evolution — relationship surviving transformed, or ending honestly.`,
    shadow: `Breakthrough overextends into destruction for its own sake; Change outpaces what the body can hold. Or Culture over-holds and the crisis is suppressed — the form preserved past its life. Or Compassion over-functions and protects the form from necessary breaking.`,
    adjacency: `Across Practice-pair: Fertile Transform softens crisis into composting; Load-Bearing Truth makes it about what structurally must carry; Gentle Stewardship matures it into the elder's practice of tending what will pass. Across Activity-pair: Commanded Power aims pressure; Anatomy of Relation dissects the pattern; Revolution converts pressure into new order.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Relational Crisis" names the phenomenon exactly — the point where relationship and form must reckon.',
  },

  'Revolution': {
    definition: `Revolution is the neighborhood where intensity completes its arc by making new order out of broken old order. Feeling and thought meet through earth and fire — form and propulsion together — producing the mode in which pressure is converted to construction. Change releases the old. Breakthrough shatters what will not release. Drive carries the momentum. Order lays down new structure. The neighborhood IS the phenomenon of necessary overthrow — not destruction for its own sake, but the directed demolition that clears ground so a better architecture can stand.`,
    whyFour: `Intensity at the mode of Creative Building is the phase where accumulated pressure becomes new structure. Change and Breakthrough supply the release and the shatter. Drive supplies the heat to keep moving through the wreckage. Order — critically — supplies the new framework; without it, revolution is merely chaos. Remove Order and the revolution produces a vacuum filled by the worst of what was overthrown. The Structure+Intent Activity-pair is what makes revolution constructive rather than merely destructive — it insists on a blueprint for after.`,
    collapseMeans: `Identity collapses. The neighborhood burns through fixed selves. Who the revolutionary was cannot survive the revolution; who they will become is not yet clear. Revolution requires loosened identity to work — the person or culture that cannot let go of its old self cannot successfully overthrow it. Identity goes liminal for the duration of the arc's completion.`,
    practical: `The overthrow that was coming. The employee who finally quits and takes others with them. The movement that topples a regime and has a constitution ready. The individual who burns their life down and rebuilds it intentionally. The scientific paradigm shift that not only disproves the old theory but names the new one. Watch for: demolition with a blueprint; the simultaneous smell of smoke and fresh lumber; the exhausted exhilaration of building on cleared ground.`,
    healthy: `Breakthrough clears only what must be cleared; Change releases with precision; Drive is channeled by Order's framework; the new structure is genuinely better. The revolution does not eat its own children.`,
    shadow: `Breakthrough overextends — endless destruction with no construction. Or Order imposes itself prematurely — the new regime mirrors the old. Or Drive burns unmoored — revolutionary zeal without ethical framework. Revolution's shadow is the revolution that fails to install the better order and thereby makes the case for restoration.`,
    adjacency: `Across Practice-pair: Generative Force softens revolution into making without overthrow; Foundation makes it structural; Grace matures it into the wisdom of not-overthrowing. Across Activity-pair: Commanded Power is revolution's prelude; Anatomy of Relation dissects the dynamic that made revolution necessary; Relational Crisis is the pressure-point that preceded revolution by one tick.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Revolution" is the correct common term for intensity-arc\'s creative-building completion; no refinement improves it.',
  },

  'Price of Knowing': {
    definition: `Price of Knowing is the neighborhood where seeing clearly costs something. Thought and form meet through fire and air — intent and cognition together — producing the mode in which understanding requires discipline and surrender. Order establishes the framework. Sacrifice releases what blocks the view. Abstraction reveals the binding pattern. Discipline cultivates the eye. The neighborhood IS the phenomenon of what you must give up to see clearly — the expertise paid for in hours, the wisdom paid for in illusions lost, the pattern recognition that could only arrive after enough of the old seeing had died.`,
    whyFour: `Structure at the mode of Directed Perception asks: what does it take to know something hard? Order provides the framework within which knowing becomes possible. Abstraction reveals the underlying pattern. Discipline supplies the sustained attention that turns raw capacity into expert sight. Sacrifice releases the attachments that distort perception. Remove Sacrifice and the knowing is blocked by what the knower won't release. Remove Discipline and the sight is never cultivated.`,
    collapseMeans: `Identity collapses. The knower's Identity loosens as the seeing costs the seer something of who they were. Real knowing changes you. The neighborhood insists that the price of clear sight is loss of the self that could not see. Identity goes soft so perception can go hard.`,
    practical: `The hard-won clarity of someone who has done the work. The doctor who can read the x-ray because they've read ten thousand. The therapist who recognizes the pattern because they sacrificed the reflex to rescue. The scholar whose thesis required them to give up the tradition that raised them. Watch for: knowledge carried without bravado; the quiet of expertise; the small grief that accompanies sight.`,
    healthy: `The four members cooperate — Order frames, Discipline cultivates, Abstraction reveals, Sacrifice releases. The knower pays the price with eyes open and the knowing serves.`,
    shadow: `Sacrifice overextends into martyrdom-as-expertise ("look what I gave up"). Or Abstraction becomes pattern-seeing as domination. Or Discipline becomes perfectionism. Or Order becomes academic rigidity — framework mistaken for truth.`,
    adjacency: `Across Practice-pair: Commanded Power softens price-of-knowing into authority; Tested Truth softens it into communal verification; Foundation shifts it into building. Across Activity-pair: Luminous Direction lightens it with aspiration; Sacred Witness matures it into presence without the knowing-ambition; Silent Knowing carries the same cost but without the directed sharpness.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Price" holds the Sacrifice+Discipline cost-structure; "Knowing" holds the Order+Abstraction cognitive completion.',
  },

  'Tested Truth': {
    definition: `Tested Truth is the neighborhood where claims are verified by lived exchange. Thought and form meet through air and water — cognition and resonance together — producing the mode in which what is held to be true is checked against what actually works in relationship. Abstraction proposes the pattern. Discipline practices it. Culture transmits and validates it. Equity measures whether it holds in fair exchange. The neighborhood IS the phenomenon of truth that has survived testing by a community of practitioners — not the truth of argument but the truth of what still stands after many people have tried to use it.`,
    whyFour: `Structure at the mode of Relational Knowing must solve the verification problem: how do we know what we know? Abstraction proposes the model. Discipline practices it over time. Culture provides the community within which the practice is checked. Equity provides the fair-measure that catches self-deception. Remove Equity and the testing is corrupted by favoritism. Remove Culture and the truth is private and cannot be shared. Remove Discipline and the test is superficial. Remove Abstraction and there is no claim to test.`,
    collapseMeans: `Stage collapses. The four-fold Stage distinction narrows to two — Medium and Fruition. The Seed (first proposal) and Feedback (full integration) are absent; the neighborhood lives in the middle of the work: the ongoing practice and the completed-but-not-yet-returned result. When truth is being tested, you are neither starting nor finished — you are in the long middle of use.`,
    practical: `The mature disciplines — medicine, craft, martial art, therapy, software engineering — where claims survive because they keep working. The protocol that has been applied ten thousand times and still produces the result. The translation that generations of translators have refined. The recipe that the family has cooked for fifty years. Watch for: calm confidence based on long use rather than argument; the readiness to be shown wrong; the humility of practitioners who know the conditions under which their truth fails.`,
    healthy: `Abstraction, Discipline, Culture, and Equity cooperate to produce durable shared knowledge. The tradition is living — it refines and corrects itself. Practitioners hold their knowledge lightly because they know how it was earned.`,
    shadow: `Culture ossifies into dogma and the testing stops. Or Equity becomes tribal — only certain members' tests count. Or Abstraction over-reifies the model so counterexamples are dismissed. Or Discipline becomes guild-gatekeeping. The shadow of Tested Truth is a tradition that once was tested and no longer is.`,
    adjacency: `Across Practice-pair: Anatomy of Relation softens tested truth into examined relationship; Load-Bearing Truth shifts it into what must carry weight; Silent Knowing matures it into wordless practice. Across Activity-pair: Price of Knowing sharpens it into directed individual perception; Foundation converts it into intentional building.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Tested" holds the Discipline+Equity verification process; "Truth" holds the Abstraction+Culture claim-and-tradition.',
  },

  'Load-Bearing Truth': {
    definition: `Load-Bearing Truth is the neighborhood where truth must hold actual weight. Thought and form meet through water and earth — resonance and structure together — producing the mode in which shared knowing becomes architecture that carries load. Culture transmits the tradition. Equity distributes fairly. Breakthrough tests what can't hold. Fortitude bears what can. The neighborhood IS the phenomenon of the truth that has to stand up — the wall that must not fall, the promise that must be kept, the institution that actually holds its people, the ethics that survive an actual crisis.`,
    whyFour: `Structure at the mode of Grounded Holding is the phase where truth stops being merely proposed or verified and starts being used as a support. Fortitude supplies the capacity to carry weight. Breakthrough supplies the testing lightning that reveals which truths were load-bearing and which were ornamental. Equity supplies the fair distribution that keeps the load shared. Culture supplies the transmission that makes the load-bearing truth available to the next generation.`,
    collapseMeans: `Identity collapses. The carrier's Identity narrows — who bears the weight becomes less a question of individual self and more a question of whether the weight is being borne at all. When a truth is actually load-bearing, the bearer is subordinated to the bearing. The work is larger than the worker. Identity softens because the weight is what matters.`,
    practical: `The promises that are kept through adversity, the institutions that survive their founders, the cultural practices that still work in crisis. The family whose love holds through the worst year. The legal principle that survives a corrupt administration. The engineering tolerance that kept the bridge standing in the earthquake. Watch for: truth whose standing is demonstrated by what it carries rather than what it claims; the humility of systems that have actually been tested.`,
    healthy: `Culture transmits, Equity distributes, Breakthrough tests, Fortitude bears. The load is shared and the structure stands. The people inside the structure can trust it because the structure has been shown to hold.`,
    shadow: `Fortitude overextends and one bearer takes all the weight (the stoic who carries what should have been distributed). Or Culture ossifies and the load-bearing is ritual rather than real. Or Breakthrough over-tests and the bearers exhaust themselves proving the structure holds. Or Equity becomes nominal — the appearance of fair distribution without the substance.`,
    adjacency: `Across Practice-pair: Relational Crisis lightens load-bearing into pressure-point; Tested Truth softens it into verification; Gentle Stewardship matures it into elder care. Across Activity-pair: Price of Knowing individuates the cost; Foundation converts it into intentional building.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Load-Bearing" names the Fortitude+Equity work; "Truth" names the Culture+Breakthrough claim-and-test.',
  },

  'Foundation': {
    definition: `Foundation is the neighborhood where structure is built deliberately to hold whatever comes next. Thought and form meet through earth and fire — structure and intent together — producing the mode in which building is conscious, bedrock, and oriented toward the future. Breakthrough clears the site. Fortitude sets the footings. Order lays the grid. Sacrifice releases what the foundation cannot include. The neighborhood IS the phenomenon of the bedrock layer — what remains after everything unnecessary has been cleared away, constructed on purpose to carry what will be built above it.`,
    whyFour: `Structure at the mode of Creative Building is the terminal phase of the arc — the place where all the earlier work (knowing, truth, load-bearing) becomes actual construction. Breakthrough clears away what cannot be built on. Fortitude supplies the strength to hold the foundation under pressure. Order supplies the geometric framework. Sacrifice supplies the willingness to exclude what will not fit. Remove any and the foundation fails.`,
    collapseMeans: `Stage collapses. The four-fold Stage distinction narrows to two — Seed and Feedback. The neighborhood is entirely about the beginning and the return; the middle stages belong to what will be built on the foundation, not the foundation itself. Foundation work is not the doing-the-thing; it is the clearing-and-first-laying and the inspection-after. You do not inhabit a foundation; you build upon it.`,
    practical: `The structural work that precedes every serious building. The constitutional convention. The business plan that will outlast its founders. The therapeutic frame that will hold many sessions. The body of research that will enable a field. Watch for: work that does not seek applause because it is not yet visible; the willingness to clear and to exclude; the sobriety of construction that knows it must outlast the builder.`,
    healthy: `The four members cooperate — Breakthrough clears honestly, Fortitude holds without gripping, Order structures without rigidifying, Sacrifice excludes without bitterness. The foundation is both deep and generous enough to hold what will come.`,
    shadow: `Order overextends and the foundation becomes too specific — it can only support what was foreseen. Or Sacrifice overextends and the foundation is so austere nothing can grow from it. Or Breakthrough under-clears and the foundation rests on buried rot. Or Fortitude stiffens and the foundation cannot flex with load.`,
    adjacency: `Across Practice-pair: Generative Force softens foundation into making; Revolution intensifies it into overthrow-with-blueprint; Grace matures it into the wisdom of foundations that do not grasp. Across Activity-pair: Price of Knowing individuates the cost of foundation; Tested Truth provides the verification that informs foundation; Load-Bearing Truth shows what the foundation must carry.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Foundation" names precisely the Mind+Body × Structure+Intent phenomenon — the bedrock laid on purpose.',
  },

  'Sacred Witness': {
    definition: `Sacred Witness is the neighborhood where presence sees without acting. Form and aspiration meet through fire and air — intent and cognition together — producing the mode in which consciousness stands in the presence of what is, aimed and discerning, but without converting the seeing into intervention. Sacrifice releases the reflex to fix. Inspiration supplies the light that illuminates without interrogating. Discipline supplies the cultivated capacity to stay. Wisdom supplies the direct perception. The neighborhood IS the phenomenon of bearing witness — the attending that honors rather than processes, the sight that holds both the beautiful and the terrible without flinching or grasping.`,
    whyFour: `Wisdom at the mode of Directed Perception is a specific discipline: aimed seeing that does not act. Wisdom's silent perception anchors the neighborhood. Discipline's cultivated attention makes staying possible. Inspiration's radiance provides the lit presence that witnessing requires. Sacrifice's release of the impulse to intervene is what makes witness rather than engagement. Remove Sacrifice and you get rescuer. Remove Discipline and the attention breaks. Remove Inspiration and witnessing becomes bleak. Remove Wisdom and the witnessing lacks depth.`,
    collapseMeans: `Being collapses. The witness does not differentiate what-is-happening into named categories. Phenomenologically: the witness does not sort the scene into "joy" and "grief" and "fear" — the scene is held whole, and the four-fold of Being dissolves into simple presence-with. The occurrence is allowed its full character without being reduced.`,
    practical: `The capacity to be with the dying, the grieving, the birthing, the traumatized, without needing to do. The midwife who knows when not to intervene. The friend who sits without advising. The reader who receives the difficult book without rushing to resolve it. The elder who watches the younger person make the mistake that will teach them. Watch for: the quiet that is not distance; the steadiness that is not indifference; the tears that arrive without performance.`,
    healthy: `The four members produce attending that serves. The witnessed feels seen, not examined. The witness leaves with their integrity and the witnessed with theirs.`,
    shadow: `Sacrifice overextends into passivity disguised as witnessing — refusal to help when help was needed. Or Discipline rigidifies into cold observation. Or Inspiration becomes spiritual bypass ("I'm holding space") while the actual suffering is ignored. Or Wisdom dissociates into the pose of wisdom without the substance.`,
    adjacency: `Across Practice-pair: Luminous Direction sharpens witness into aim; Commanded Power converts it into authority; Price of Knowing shifts it into costly knowing. Across Activity-pair: Silent Knowing softens witness into wordless knowing; Gentle Stewardship extends it into tending; Grace matures it into non-grasping action.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Sacred" holds the Inspiration+Wisdom spiritual depth; "Witness" holds the Sacrifice+Discipline non-interfering attention.',
  },

  'Silent Knowing': {
    definition: `Silent Knowing is the neighborhood where understanding is so deeply integrated that words are neither needed nor available. Form and aspiration meet through air and water — cognition and resonance together — producing the mode in which knowing is a quality of presence rather than a content. Discipline has cultivated it over time. Wisdom perceives it directly. Equity measures it fairly without speaking. Imagination holds its symbolic depth. The neighborhood IS the phenomenon of knowledge that has passed from explicit to tacit — the practitioner whose hands know, the elder whose presence teaches, the reader who understands the text without being able to summarize it.`,
    whyFour: `Wisdom at the mode of Relational Knowing is where Body's long practice meets Spirit's long perception. Discipline supplies the cumulative practice that allows knowing to become bodily. Wisdom supplies the direct perception that remains active inside the silence. Equity supplies the fair-measure that keeps the silent knower honest. Imagination supplies the symbolic depth that makes wordless knowing meaningful rather than blank. Remove Discipline and the silence is empty. Remove Wisdom and it is merely habit.`,
    collapseMeans: `Identity collapses. The knower's Identity narrows — the self that would have the knowledge and claim it dissolves into the knowing itself. The silent knower is less a person-who-knows and more a person-through-whom-knowing-moves. Identity softens to make the silence possible; a loud identity cannot sustain silent knowing.`,
    practical: `The masters whose teaching is mostly presence. The therapist whose interventions are few and precisely placed. The craftsman whose apprentices learn by watching. The grandmother whose decisions are trusted though she rarely explains them. Watch for: knowledge demonstrated rather than stated; the economy of right action without justification; the student's realization that they learned something they were never told.`,
    healthy: `The four members cooperate to produce an embodied, integrated, trustworthy presence. The silent knower can still speak when speaking serves; the silence is not withholding.`,
    shadow: `Discipline hardens into the guru-pose — silence as power move. Or Wisdom becomes mystique — pretending to know what is not known. Or Imagination dreams the silent knower into grandiosity. Or Equity hollows and the silent knower begins to judge from behind the pose. Silent Knowing's shadow is the fraud who has learned to perform it.`,
    adjacency: `Across Practice-pair: Open Reception softens silent knowing into receiving; Anatomy of Relation places it under the lens of language; Tested Truth grounds it in verifiable practice. Across Activity-pair: Sacred Witness sharpens it into directed perception; Gentle Stewardship extends it into tending; Grace matures it into action that does not grasp.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Silent Knowing" names the phenomenon precisely — knowledge held without needing to be spoken, presence that itself carries the understanding.',
  },

  'Gentle Stewardship': {
    definition: `Gentle Stewardship is the neighborhood where what has been entrusted is held without being owned. Form and aspiration meet through water and earth — resonance and structure together — producing the mode in which long tending preserves what belongs to something larger. Equity distributes fairly. Imagination honors symbolic depth. Fortitude carries the weight. Nurturing cultivates the ground. The neighborhood IS the phenomenon of elder care in its broadest sense — the parent who holds space without controlling, the teacher who maintains the tradition without grasping it, the gardener who tends what they did not plant, the executor of the estate who makes sure nothing is taken.`,
    whyFour: `Wisdom at the mode of Grounded Holding is where Body's capacity and Spirit's perception combine to tend what passes through the steward's hands. Nurturing supplies the sustaining attention. Fortitude supplies the strength to carry without crushing. Equity supplies the fair distribution that keeps stewardship from becoming ownership. Imagination supplies the vision of what the tended thing is for beyond the steward. Remove Nurturing and the stewardship lacks care. Remove Fortitude and the steward collapses under load. Remove Equity and stewardship slides into proprietorship.`,
    collapseMeans: `Being collapses. What is happening in the neighborhood cannot be reduced because stewardship simultaneously holds many occurrences: tending, grieving, teaching, releasing. The good steward is not doing one thing at a time; they are doing several things at once, and the neighborhood requires Being to collapse so the multiple occurrences can co-exist without needing to be sorted.`,
    practical: `The long tending of what is precious. The mother of adult children who maintains the thread without pulling. The librarian who preserves the collection for readers unborn. The ecosystem manager who thinks in centuries. The language teacher keeping a minority tongue alive. Watch for: patience that is not resignation; authority that does not claim; the careful light touch of someone who knows they are passing through.`,
    healthy: `The four members cooperate to produce tending that serves what is being tended rather than the tender. The steward is evident in their absence as much as their presence — things are held without being clutched.`,
    shadow: `Nurturing overextends into smother — stewardship becomes possession. Or Fortitude rigidifies into control. Or Equity becomes officious rule-enforcement. Or Imagination drifts into idealization and the actual thing is no longer tended. Gentle Stewardship's shadow is the "steward" who has quietly become owner.`,
    adjacency: `Across Practice-pair: Fertile Transform softens stewardship into composting; Relational Crisis intensifies it into pressure; Load-Bearing Truth structuralizes it into carrying. Across Activity-pair: Sacred Witness sharpens it into directed witness; Silent Knowing moves it into relational wordless knowing; Grace matures it into non-grasping action.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Gentle" holds the Nurturing+Imagination quality of touch; "Stewardship" holds the Fortitude+Equity work of carrying-without-owning.',
  },

  'Grace': {
    definition: `Grace is the neighborhood where action happens without grasping. Form and aspiration meet through earth and fire — structure and intent together — producing the mode in which doing flows from integrated being rather than effort. Fortitude holds. Nurturing tends. Sacrifice releases. Inspiration radiates. The neighborhood IS the phenomenon of the lightest touch carrying the heaviest weight — the capacity to build, lead, create, and act from a place so integrated that the action itself seems almost unauthored. The master's economy. The dancer at the top of their art. The leader whose decisions look inevitable in retrospect. Doing that has become being.`,
    whyFour: `Wisdom at the mode of Creative Building completes the arc: long body (Fortitude, Nurturing) and long spirit (Sacrifice, Inspiration) have matured together long enough that action no longer requires the straining of any single capacity. Fortitude supplies the bedrock capacity. Nurturing keeps the doing relational. Sacrifice releases the grip that would make the action effortful. Inspiration supplies the radiant aim. Remove Sacrifice and the action becomes effort; the grace goes. Remove Fortitude and there is no capacity to make effortless.`,
    collapseMeans: `Identity collapses. The grace-acting person is not asserting self through the action. The maker disappears into the making. Grace is unselfconscious — watch a master at work and their Identity is quiet; they are the act, not a person doing the act. When Identity reasserts — when the actor becomes aware of themselves as actor — the grace fails.`,
    practical: `The upper reaches of any long-developed capacity. The surgeon whose hands do not shake at the hard moment. The teacher whose explanation arrives exactly at the moment the student could receive it. The parent whose firmness and tenderness are not two things. The musician whose performance disappears the musician. Watch for: actions that look easy because they have been difficult for decades; the economy that only very practiced people achieve; the absence of strain.`,
    healthy: `The four members are so integrated that the neighborhood is visible only in its effects. The grace-acting person does not know they are acting gracefully; if they did, they would no longer be.`,
    shadow: `Sacrifice performs release that is actually accumulation — grace as spiritual pose. Or Inspiration radiates what has not been cultivated — charisma mistaken for grace. Or Fortitude pretends to ease while carrying rigidity underneath. Or Nurturing becomes the performance of warmth without the substance. Grace's shadow is the impersonation of grace.`,
    adjacency: `Across Practice-pair: Generative Force softens grace into making-as-force; Revolution intensifies it; Foundation structuralizes it. Across Activity-pair: Sacred Witness sharpens grace into directed presence; Silent Knowing moves it into relational wordless knowing; Gentle Stewardship extends it into long tending.`,
    confidence: 'Derived',
    nameStatus: 'Existing name confirmed. "Grace" is the correct and traditional name for the Wisdom-arc completion in Creative Building mode — a single word because the phenomenon resists modification.',
  },
};

// Support lookup by existing name key in explore/page.js NEIGHBORHOODS (which uses 'Anatomy of Relation')
// Alias any short-form keys used in the app to the canon keys here.
export const NEIGHBORHOOD_CANON_ALIASES = {
  'Anatomy of Relation': 'Anatomy of Relation',
};
