// BENCH — READABILITY (the campaign opened 2026-10-05 by the founder with Air). A fresh cheap-lane instance is handed a Plain opening with
// NO architecture explained and asked the six questions: (1) in one sentence, what did it tell you? (2) what does it want you to do? (3) which
// sentence did you have to reread? (4) which sounded meaningful but you couldn't explain literally? (5) where did it use an image when plain
// English would have been clearer? (6) rewrite it in words you'd say to a friend. A second call grades the paraphrase (1) against the gist the
// Reader wrote: MATCH / PARTIAL / MISS — the killer metric: if the reader cannot paraphrase it after one read, Plain has failed.
// Readings: the founder's exhibit (the upload) + the L bench's live-lane Plain openings (12 mechanism + 6 personal). Writes markdown to the shelf.
//   npx tsx scripts/bench_readability.mjs
import fs from 'node:fs';
const ENV = fs.readFileSync('.env.local', 'utf8'); for (const line of ENV.split(/\r?\n/)) { const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/); if (m && !line.trim().startsWith('#') && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, ''); }
const { callProvider } = await import('../lib/provider.js');
const { MODEL_IDS } = await import('../lib/modelConfig.js');
const ask = async (system, user, max = 900) => { const { data } = await callProvider({ model: MODEL_IDS.sonnet, max_tokens: max, system, messages: [{ role: 'user', content: user }] }, { tag: 'readability' }); if (data?.error) throw new Error(data.error.message); return data.content?.map((i) => i.text || '').join('\n') || ''; };

// --- the readings
const readings = [];
const ex = fs.readFileSync('C:/Users/chris/.claude/uploads/4466b7a6-0b7d-4675-8061-9b56f052ad10/a6244c8c-nirmanakaya-ez-2026-10-05.md', 'utf8');
{ const q = (ex.match(/\*\*Asked:\*\* (.+)/) || [])[1]; const body = ex.split('**Reader:**')[1].split('## The doors')[0].trim(); const gist = (body.match(/^\*(.+?)\*$/m) || [])[1] || ''; const med = (body.match(/^> ◈ ?(.*)$/m) || [])[1] || ''; const question = (body.match(/\n\*([^*\n]+\?)\*\s*$/) || [])[1] || ''; const prose = body.replace(/^\*(.+?)\*$/m, '').replace(/^> ◈.*$/m, '').replace(/\n\*[^*\n]+\?\*\s*$/, '').trim(); readings.push({ key: 'exhibit · quiet my mind', question: q, gist, prose, medicine: med, closing: question, draw: 'Too Little Executor of Intent in Recognition' }); }
// INPUT: default = the L bench's live lane (the baseline); or `--file <bench md> --lane <A|B|live|<name>>` to read another bench's lane
// (a key line "X: A = <name>, B = <name>" picks the lane by name; otherwise the letter is used as given), and `--out <shelf filename>`.
const arg = (k, d) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : d; };
const FILE = arg('--file', 'G:/My Drive/For Air Review/BENCH_Candidate_L_Level_Of_Address_2026-10-05.md'); const LANE = arg('--lane', 'live'); const OUT = arg('--out', 'BENCH_True_Readability_Six_Questions_2026-10-05.md'); const NO_EXHIBIT = process.argv.includes('--no-exhibit');
if (NO_EXHIBIT) readings.length = 0;
const L = fs.readFileSync(FILE, 'utf8');
const keyLines = L.split('## The key')[1] || ''; const laneByKey = Object.fromEntries([...keyLines.matchAll(/^- (.+?): A = ([^,]+), B = (.+)$/gm)].map((m) => [m[1].trim(), m[2].trim() === LANE ? 'A' : m[3].trim() === LANE ? 'B' : null]));
for (const part of L.split(/^## /m).slice(1)) {
  const key = part.split('\n')[0].trim(); if (/^The key|^The verdict/.test(key)) continue; const lane = laneByKey[key] || (/^[AB]$/.test(LANE) ? LANE : null); if (!lane) continue;
  const q = (part.match(/\*\*Q:\*\* (.+)/) || [])[1] || ''; const blocks = part.split(/^### /m).slice(1); const b = blocks.find((x) => x[0] === lane); if (!b) continue;
  const body = b.slice(1).trim(); const gist = (body.match(/^\*(.+?)\*$/m) || [])[1] || ''; const med = (body.match(/^> ◈ ?(.*)$/m) || [])[1] || ''; const closing = (body.match(/\n\*([^*\n]+\?)\*\s*$/) || [])[1] || ''; const prose = body.replace(/^\*(.+?)\*$/m, '').replace(/^> ◈.*$/m, '').replace(/\n\*[^*\n]+\?\*\s*$/, '').trim();
  readings.push({ key: `${FILE.split('/').pop().replace('BENCH_', '').replace(/_2026.*$/, '')} · ${key} (${LANE})`, question: q.replace(/\(no question.*\)/, '').trim(), gist, prose, medicine: med, closing, draw: (part.match(/\*\*Draw:\*\* (.+)/) || [])[1] || '' });
}
console.log(`${readings.length} readings`);

const READER_SYS = 'You are an ordinary, intelligent adult. You have never heard of this system and nobody will explain it to you. You asked the question shown and received the reading shown. Answer the eight questions honestly and briefly, in plain English, as yourself. Do not flatter the reading. Number your answers 1–8.';
// EFFORT and FRIEND (Air, 2026-10-05): comprehension alone misses the experience — a reading can "match" and still be laborious and weird.
// 7. EFFORT 0–3: 0 transparent (understood as written) · 1 friction (reread or mentally translated a phrase) · 2 work (meaning recovered, but
// several sentences needed decoding) · 3 opaque (could not confidently recover the meaning). 8. FRIEND pass/fail: would a friend who is on
// your side say this, this way — fails if it hedges, diminishes, performs, lectures, or talks about your life in nouns that aren't yours.
const Q9 = '\n9. READING LEVEL: the US school grade at which a typical student could read this and say what it told them — answer "9. grade <number>" (K = 0; adult/college = 13).';
const Q78 = '\n7. EFFORT, one digit: 0 = transparent, you understood it as written; 1 = friction, you reread or mentally translated a phrase; 2 = work, you got the meaning but several sentences needed decoding; 3 = opaque, you could not confidently recover the meaning. Answer "7. <digit> — <one short reason>".\n8. FRIEND: would a friend who is genuinely on your side say this to you, this way? Answer "8. pass" or "8. fail — <quote the one sentence that gives it away>" (a friend does not hedge, does not make you smaller, does not perform wisdom, does not lecture or assign homework, and talks about your life in your own nouns).';
const GRADER_SYS = 'You compare two short texts. The first is what a reading was MEANT to say. The second is what an ordinary reader said it told them after one read. Answer with one token — MATCH if the reader\'s sentence carries the meant text\'s main point; PARTIAL if it carries part of it or adds a different point; MISS if it misses or contradicts it — then one short sentence saying why.';
// TWO REFERENCES (Air, 2026-10-05): the Reader's own gist can be fuzzy or wrong, so matching it proves little on its own. Reference A = the
// structural meaning built from the record for the draw (status + capacity + seat + the partner's acts); reference B = the gist. Four cases:
// A&B match = success · B only = the gist was off (interpretation) · A only = the gist obscured a right structure (gist problem) · neither = Plain failed.
const { getComponent } = await import('../lib/corrections.js');
const { buildKernel } = await import('../lib/kernel.js');
const { MEDICINE_ACTS } = await import('../lib/pour/medicineActs.js');
const DEFS = (await import('../lib/data/nirmanakaya_78_definitions.json', { with: { type: 'json' } })).default;
const idOf = (n) => { for (let i = 0; i < 78; i++) if (getComponent(i)?.name === n) return i; };
// THE STRUCTURE CHECK (replacing the first reference-A sentence, which never matched anything — a dense record-built line is not what a
// stranger's paraphrase will ever equal): two yes/no questions to the grader, from the draw's facts. (i) Does the paraphrase carry the
// FIRST signature's status direction — under-done / over-done / done-but-not-owned / working? (ii) Does the reader's stated action carry
// the partner's act? Structure = both yes.
const STATUS_DIR = { Balanced: 'the capacity is WORKING, as their own, now (nothing to fix)', 'Too Much': 'the capacity is being done MORE than the moment asks (over-done, pushed ahead)', 'Too Little': 'the capacity is being done LESS than the moment asks (under-done, held back, not arriving)', Unacknowledged: 'the capacity IS being done, but the person is NOT holding it as their own (the credit goes elsewhere)' };
const factsOf = (drawLine) => { const m = (drawLine || '').split(' · ')[0]?.match(/^(Balanced|Too Much|Too Little|Unacknowledged) (.+?) in (.+)$/); if (!m) return null; const t = idOf(m[2]), p = idOf(m[3]); const c = getComponent(t); let partner = null; try { partner = buildKernel({ transient: t, position: p, status: { Balanced: 1, 'Too Much': 2, 'Too Little': 3, Unacknowledged: 4 }[m[1]] }, DEFS)?.partnerId ?? null; } catch {} return { status: m[1], dir: STATUS_DIR[m[1]], capacity: c?.description || c?.name, acts: partner != null && MEDICINE_ACTS[partner] ? MEDICINE_ACTS[partner].acts.join(' · ') : '' }; };
// THE GIST AGAINST THE STRUCTURE (Air's table needs the structure → gist link too): the same two questions asked of the Reader's own gist + medicine.
const GIST_SYS = 'You check two things about a reading\'s own one-line summary and its stated way through. You are given the draw\'s facts: the capacity in question, its status direction, and the canonical acts of the way through. Answer on two lines exactly: "STATUS: yes|no" — does the summary carry that status direction (paraphrase counts)? "ACT: yes|no" — does the way through carry one of the canonical acts (paraphrase counts)?';
const STRUCT_SYS = 'You check two things about what an ordinary reader took from a reading. You are given the draw\'s facts: the capacity in question, its status direction, and the canonical acts of the way through. Then the reader\'s two answers. Answer on two lines exactly: "STATUS: yes|no" — does the reader\'s one-sentence summary carry that status direction (paraphrase counts; the capacity need not be named exactly)? "ACT: yes|no|none" — does the reader\'s stated action carry one of the canonical acts (paraphrase counts), none if the reader said there was nothing to do?';
const READERS = Math.max(1, Number(arg('--readers', 3)));
const majority = (arr) => { const c = {}; for (const x of arr) c[x] = (c[x] || 0) + 1; return Object.entries(c).sort((a, b) => b[1] - a[1] || ['MATCH', 'PARTIAL', 'MISS'].indexOf(a[0]) - ['MATCH', 'PARTIAL', 'MISS'].indexOf(b[0]))[0][0]; };
const out = [`# READABILITY — the six questions on ${readings.length} Plain openings, ${READERS} fresh reader${READERS > 1 ? 's' : ''} each, no architecture explained`, `*True, 2026-10-05. Reader = the cheap lane as an ordinary adult, ${READERS} independent passes per reading; grader = the same lane. Per reading: the MAJORITY grade of the paraphrase against the gist, and the spread; plus the structure check (status direction carried? the partner's act carried?). The reread / could-not-explain / image answers are the fog corpus (first pass only).*`, ''];
const tally = { MATCH: 0, PARTIAL: 0, MISS: 0, structure: { both: 0, statusOnly: 0, actOnly: 0, neither: 0 }, gist: { both: 0, statusOnly: 0, actOnly: 0, neither: 0 }, effort: { 0: 0, 1: 0, 2: 0, 3: 0, sum: 0, n: 0 }, friend: { pass: 0, fail: 0 }, rows: {}, spread: { unanimous: 0, split: 0 }, perPass: Array.from({ length: READERS }, () => ({ MATCH: 0, PARTIAL: 0, MISS: 0 })) }; const fog = []; const friendFails = [];
for (const r of readings) {
  const shown = `${r.question ? `YOUR QUESTION: ${r.question}\n\n` : 'YOU ASKED NOTHING — it is a reading for where you are right now.\n\n'}THE READING:\n\n${r.gist}\n\n${r.prose}\n\nThe way through: ${r.medicine}\n\n${r.closing}`;
  const facts = factsOf(r.draw); const grades = []; const structs = []; const efforts = []; const friends = []; let firstA = '';
  let gistOk = null; if (facts) { const gs = await ask(GIST_SYS, `THE DRAW'S FACTS — capacity: ${facts.capacity}. Status direction: ${facts.dir}. Canonical acts of the way through: ${facts.acts || '(Balanced: an invitation, not a correction)'}.\n\nTHE READING'S SUMMARY: ${r.gist}\nTHE READING'S WAY THROUGH: ${r.medicine}`, 40); gistOk = { status: /STATUS:\s*yes/i.test(gs), act: /ACT:\s*yes/i.test(gs) }; tally.gist[gistOk.status && gistOk.act ? 'both' : gistOk.status ? 'statusOnly' : gistOk.act ? 'actOnly' : 'neither']++; }
  for (let k = 0; k < READERS; k++) {
    const a = await ask(READER_SYS, `${shown}\n\nQUESTIONS:\n1. In one sentence, what did the reading tell you?\n2. What does it want you to do, if anything?\n3. Which sentence did you have to reread? Quote it.\n4. Which sentence sounded meaningful but you could not explain literally? Quote it.\n5. Where did it use an image or metaphor when plain English would have been clearer? Quote it.\n6. Rewrite the reading in the words you would actually say to a friend (three to five sentences).${Q78}${Q9}`, 1200);
    { const gl = (a.match(/\n\s*9\.\s*grade\s*(\d{1,2})/i) || [])[1]; if (gl !== undefined) (tally.grades = tally.grades || []).push(Number(gl)); }
    if (k === 0) firstA = a;
    { const e = (a.match(/\n\s*7\.\s*([0-3])/) || [])[1]; if (e !== undefined) efforts.push(Number(e)); const f = (a.match(/\n\s*8\.\s*(pass|fail)([^\n]*)/i) || []); if (f[1]) { friends.push(f[1].toLowerCase()); if (f[1].toLowerCase() === 'fail' && k === 0) friendFails.push(`- ${String(f[2] || '').replace(/^\s*[—-]\s*/, '').replace(/\s+/g, ' ').slice(0, 200)} — *${r.key}*`); } }
    const one = (a.match(/1\.\s*([\s\S]*?)(?=\n\s*2\.)/) || [])[1]?.trim() || a.split('\n')[0];
    const two = (a.match(/2\.\s*([\s\S]*?)(?=\n\s*3\.)/) || [])[1]?.trim() || '';
    const g = await ask(GRADER_SYS, `MEANT (the reading's own gist): ${r.gist}\n\nREADER SAID (one sentence): ${one}`, 80);
    const grade = (g.match(/MATCH|PARTIAL|MISS/) || ['MISS'])[0]; grades.push(grade); tally.perPass[k][grade]++;
    if (facts) { const s = await ask(STRUCT_SYS, `THE DRAW'S FACTS — capacity: ${facts.capacity}. Status direction: ${facts.dir}. Canonical acts of the way through: ${facts.acts || '(Balanced: an invitation to feed the capacity, not a correction)'}.\n\nREADER'S SUMMARY (1): ${one}\nREADER'S ACTION (2): ${two}`, 40); structs.push({ status: /STATUS:\s*yes/i.test(s), act: /ACT:\s*yes/i.test(s) }); }
    if (k === 0) for (const n of [3, 4, 5]) { const ans = (a.match(new RegExp(`${n}\\.\\s*([\\s\\S]*?)(?=\\n\\s*${n + 1}\\.|$)`)) || [])[1]?.trim(); if (ans) fog.push(`- (${n === 3 ? 'reread' : n === 4 ? 'could not explain' : 'image'}) ${ans.replace(/\s+/g, ' ').slice(0, 220)} — *${r.key}*`); }
  }
  const grade = majority(grades); tally[grade]++; if (new Set(grades).size === 1) tally.spread.unanimous++; else tally.spread.split++;
  const st = structs.length ? { status: structs.filter((x) => x.status).length * 2 > structs.length, act: structs.filter((x) => x.act).length * 2 > structs.length } : null;
  if (st) tally.structure[st.status && st.act ? 'both' : st.status ? 'statusOnly' : st.act ? 'actOnly' : 'neither']++;
  const effort = efforts.length ? Math.round(efforts.reduce((a, b) => a + b, 0) / efforts.length * 10) / 10 : null; if (effort !== null) { tally.effort.sum += effort; tally.effort.n++; tally.effort[Math.round(effort)]++; }
  const friend = friends.length ? (friends.filter((x) => x === 'pass').length * 2 >= friends.length ? 'pass' : 'fail') : null; if (friend) tally.friend[friend]++;
  // AIR'S TABLE: structure → gist (is the Reader's own gist faithful?), gist → reader (did the stranger get the gist?), plus effort and friend
  const row = !gistOk ? 'n/a' : (gistOk.status && gistOk.act) ? (grade === 'MATCH' ? (effort !== null && effort <= 0.5 && friend !== 'fail' ? 'clean success' : effort !== null && effort >= 1 ? 'comprehensible, not approachable' : friend === 'fail' ? 'humanity/voice failure' : 'clean success') : 'readability failure') : (grade === 'MATCH' ? 'interpretation failure (reader matched a weak gist)' : 'interpretation + readability');
  tally.rows[row] = (tally.rows[row] || 0) + 1;
  out.push(`## ${r.key}`, r.question ? `**Q:** ${r.question}` : '**Q:** (none — right now)', `**gist (what it meant):** ${r.gist}`, facts ? `**the draw's facts:** ${facts.status} — ${facts.capacity}; the way through: ${facts.acts || '(Balanced)'}` : '', gistOk ? `**the gist against the structure:** status ${gistOk.status ? 'yes' : 'no'} · act ${gistOk.act ? 'yes' : 'no'}` : '', '', `**paraphrase vs gist: ${grade}** (passes: ${grades.join(' / ')}) · **effort ${effort ?? '?'}** (${efforts.join('/')}) · **friend ${friend ?? '?'}** (${friends.join('/')}) · **row: ${row}**`, st ? `**structure carried by the reader:** status ${st.status ? 'yes' : 'no'} · act ${st.act ? 'yes' : 'no'}` : '', '', '**the first fresh reader:**', '', firstA.trim(), '');
  process.stdout.write(`${grade.padEnd(8)} [${grades.join('/')}] effort ${effort ?? '?'} friend ${friend ?? '?'} ${st ? `status ${st.status ? 'Y' : 'n'} act ${st.act ? 'Y' : 'n'}` : ''} → ${row} · ${r.key}\n`);
}
out.splice(3, 0, `**Paraphrase after one read (majority of ${READERS}): MATCH ${tally.MATCH} · PARTIAL ${tally.PARTIAL} · MISS ${tally.MISS} of ${readings.length}** — unanimous ${tally.spread.unanimous}, split ${tally.spread.split}; per pass: ${tally.perPass.map((p) => `${p.MATCH}/${p.PARTIAL}/${p.MISS}`).join(' · ')}. **The gist against the structure:** both ${tally.gist.both} · status only ${tally.gist.statusOnly} · act only ${tally.gist.actOnly} · neither ${tally.gist.neither}. **Structure carried by the reader (majority):** both ${tally.structure.both} · status only ${tally.structure.statusOnly} · act only ${tally.structure.actOnly} · neither ${tally.structure.neither}. **EFFORT** mean ${tally.effort.n ? Math.round(tally.effort.sum / tally.effort.n * 100) / 100 : '?'} (0 transparent … 3 opaque; readings at 0: ${tally.effort[0]}, 1: ${tally.effort[1]}, 2: ${tally.effort[2]}, 3: ${tally.effort[3]}). **FRIEND** pass ${tally.friend.pass} · fail ${tally.friend.fail}. **READING LEVEL** median grade ${tally.grades?.length ? [...tally.grades].sort((a, b) => a - b)[Math.floor(tally.grades.length / 2)] : '?'} (all passes: ${(tally.grades || []).join(',')}). **Air's table:** ${Object.entries(tally.rows).map(([k, v]) => `${k} ${v}`).join(' · ')}.`, '', '## Friend failures (the sentence that gave it away, first reader)', '', ...(friendFails.length ? friendFails : ['- none']), '', '## The fog corpus (what had to be reread, could not be explained, or was an image where plain words would do)', '', ...fog, '');
const path = 'G:/My Drive/For Air Review/' + OUT; fs.writeFileSync(path, out.join('\n')); console.log('\n', JSON.stringify(tally), '\nshelf:', path);
