// CHECK — Fresh Mind's algebraic claim on the live tables: on the 16 manifest archetypes, Reduction = [[Growth, Vertical], Diagonal],
// the group generated by V, D, G has order 64, and its centre is exactly {identity, Reduction}. No model calls.
const { VERTICAL_PAIRS, DIAGONAL_PAIRS, REDUCTION_PAIRS, GROWTH_PAIRS, getComponent } = await import('../lib/corrections.js');
const M = [2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18];
const perm = (pairs) => { const p = {}; for (const i of M) { const t = pairs[i]; if (!M.includes(t)) throw new Error(`leaves the manifest: ${i}->${t}`); p[i] = t; } return p; };
const V = perm(VERTICAL_PAIRS), D = perm(DIAGONAL_PAIRS), R = perm(REDUCTION_PAIRS), G = perm(GROWTH_PAIRS);
const key = (p) => M.map((i) => p[i]).join(',');
const comp = (a, b) => { const p = {}; for (const i of M) p[i] = a[b[i]]; return p; }; // (a∘b)(x) = a(b(x))
const inv = (a) => { const p = {}; for (const i of M) p[a[i]] = i; return p; };
const E = {}; for (const i of M) E[i] = i;
const comm = (a, b) => comp(comp(a, b), comp(inv(a), inv(b))); // [a,b] = a b a⁻¹ b⁻¹
const isInv = (p) => M.every((i) => p[p[i]] === i);
console.log('V, D, G, R are involutions:', [V, D, G, R].map(isInv).join(' '));
const c1 = comm(comm(G, V), D), c2 = comm(D, comm(G, V));
console.log('R == [[G,V],D]:', key(c1) === key(R), '| R == [D,[G,V]]:', key(c2) === key(R));
// generate the group
const seen = new Map([[key(E), E]]); let frontier = [E];
while (frontier.length) { const next = []; for (const x of frontier) for (const g of [V, D, G]) { const y = comp(g, x); const k = key(y); if (!seen.has(k)) { seen.set(k, y); next.push(y); } } frontier = next; }
const els = [...seen.values()];
console.log('|<V,D,G>| =', els.length);
const centre = els.filter((z) => els.every((x) => key(comp(z, x)) === key(comp(x, z))));
console.log('centre size', centre.length, '| centre = {e, R}:', centre.length === 2 && centre.some((z) => key(z) === key(R)) && centre.some((z) => key(z) === key(E)));
console.log('R in group:', seen.has(key(R)));
// transitive on the 16?
const orbit = new Set([2]); let fr = [2]; while (fr.length) { const nx = []; for (const i of fr) for (const g of [V, D, G]) { const j = g[i]; if (!orbit.has(j)) { orbit.add(j); nx.push(j); } } fr = nx; }
console.log('orbit of one point under V,D,G:', orbit.size, '/ 16');
// lower bound: is the group generated by any two of its elements? (abelianization C2^3 ⇒ no) — brute force over pairs
let two = false; outer: for (let a = 0; a < els.length; a++) for (let b = a; b < els.length; b++) { const s = new Map([[key(E), E]]); let f = [E]; while (f.length) { const n = []; for (const x of f) for (const g of [els[a], els[b]]) { const y = comp(g, x); const k = key(y); if (!s.has(k)) { s.set(k, y); n.push(y); } } f = n; } if (s.size === els.length) { two = true; break outer; } }
console.log('generated by some TWO elements:', two);
// --- what IS the central element, and how does it differ from the live Reduction?
const { BEING_GROUPS, IDENTITY_GROUPS } = await import('../lib/constants.js');
const grp = (groups, id) => Object.keys(groups).find((g) => groups[g].members.includes(id));
const PEL = { Spirit: 'Fire', Mind: 'Air', Emotion: 'Water', Body: 'Earth' }, AEL = { Intent: 'Fire', Cognition: 'Air', Resonance: 'Water', Structure: 'Earth' };
const bit = (e) => (e === 'Fire' || e === 'Earth' ? 0 : 1);
const addr = (i) => { const c = getComponent(i); return [bit(PEL[c.house]), bit(AEL[c.channel]), bit(BEING_GROUPS[grp(BEING_GROUPS, i)].element), bit(IDENTITY_GROUPS[grp(IDENTITY_GROUPS, i)].element)]; };
const flipsOf = (p) => { const s = new Set(); for (const i of M) { const a = addr(i), b = addr(p[i]); s.add(['P', 'A', 'B', 'I'].filter((_, k) => a[k] !== b[k]).join('+') || 'none'); } return [...s].join(' | '); };
const Z = centre.find((z) => key(z) !== key(E));
const name = (i) => getComponent(i).name;
console.log('\ncentral element pairs:', M.filter((i) => i < Z[i]).map((i) => `${name(i)}↔${name(Z[i])}`).join(', '));
console.log('live Reduction pairs:  ', M.filter((i) => i < R[i]).map((i) => `${name(i)}↔${name(R[i])}`).join(', '));
console.log('central element flips bits:', flipsOf(Z), '| live R flips:', flipsOf(R), '| V:', flipsOf(V), '| D:', flipsOf(D), '| G:', flipsOf(G));
console.log('[[G,V],D] pairs:', M.filter((i) => i < c1[i]).map((i) => `${name(i)}↔${name(c1[i])}`).join(', '));
console.log('central == [[G,V],D]:', key(Z) === key(c1), '| central == V∘D:', key(Z) === key(comp(V, D)), '| central == G∘V∘D∘G? ', key(Z) === key(comp(comp(G, comp(V, D)), G)));
