// LAB — THE SCAFFOLD FLOOR, DERIVED (Air's order 1, 2026-10-06: "OPERATION should be derived from the canonical act and must preserve the act
// family. A non-verbal canonical act cannot become SAY/WRITE/NAME in the scaffold"). For a draw, the cheap lane writes the four fields from the
// record and the partner's canonical acts, naming WHICH canonical act its OPERATION instantiates; then a check: the OPERATION is classified and must
// carry that act's family (lib/pour/actFamilies.json) — a verbal OPERATION only where the source act is itself verbal. One retry on a failure.
// Never touches the floor. Writes the derived scaffolds + a report to the shelf.
//   npx tsx scripts/derive_scaffold_lab.mjs corpusb      → the ten frozen Corpus B draws, compared with the hand scaffolds
//   npx tsx scripts/derive_scaffold_lab.mjs sample 60    → 60 random draws, the verbal share of the derived operations vs the poured cells' asks
import fs from 'node:fs';
const ENV = fs.readFileSync('.env.local', 'utf8'); for (const line of ENV.split(/\r?\n/)) { const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/); if (m && !line.trim().startsWith('#') && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, ''); }
const { createClient } = await import('@supabase/supabase-js');
const { buildKernel } = await import('../lib/kernel.js'); const { getComponent } = await import('../lib/corrections.js');
const { STATUS_INFO } = await import('../lib/constants.js'); const { lookupCell } = await import('../lib/pour/library.js');
const { callProvider } = await import('../lib/provider.js'); const { MODEL_IDS } = await import('../lib/modelConfig.js');
const DEFS = JSON.parse(fs.readFileSync('lib/data/nirmanakaya_78_definitions.json', 'utf8'));
const P = JSON.parse(fs.readFileSync('lib/data/plain_propositions.json', 'utf8'));
const AF = JSON.parse(fs.readFileSync('lib/pour/actFamilies.json', 'utf8')); const FAMILIES = AF._meta.families; const VERBAL = new Set(['SAY', 'WRITE', 'ASK']);
const MODE = process.argv[2] || 'corpusb'; const NS = Number(process.argv[3] || 60);
const KEY = { 1: 'balanced', 2: 'tooMuch', 3: 'tooLittle', 4: 'unacknowledged' };
const sources = (d) => {
  const sig = getComponent(d.transient) || {}, seat = getComponent(d.position) || {}, def = DEFS.signatures[d.transient] || {};
  const parentId = def.class === 'Archetype' ? d.transient : def.associatedArchetype; const parent = DEFS.signatures[parentId] || {};
  const k = buildKernel(d, DEFS); const pid = k?.partnerId; const acts = AF.signatures[String(pid)]?.acts || [];
  return { pid, partner: getComponent(pid)?.name, acts, text: [`SIGNATURE: ${sig.name} — ${sig.description}`, `SEAT: ${seat.name} — ${seat.description}`, `STATUS: ${STATUS_INFO[d.status].name} — ${P.general[d.status].plain}`, `STATE LINE: ${P.states[String(parentId)]?.[KEY[d.status]]?.plain || ''}`, d.status !== 1 ? `BACK IN BALANCE: ${P.states[String(parentId)]?.balanced?.plain || ''}` : 'BALANCED: the partner is growth, an invitation', `MEDICINE PARTNER: ${getComponent(pid)?.name}`, `THE PARTNER'S CANONICAL ACTS (numbered): ${acts.map((a, i) => `[${i + 1}] ${a.act}`).join(' · ')}`, `MECHANISM: ${P.mechanism[d.status].plain}`].join('\n') };
};
const SYS = `You write the FLOOR for one draw: four terse semantic fields, never prose. Rules: no second person; phrases, not polished sentences; no metaphor; no taught figure; no invented people, objects, times, motives, history or circumstances; no archetype or house jargon; every field traces to the material given.
CONDITION: what is happening / what is off · DOMAIN: where in the person's functioning · OPERATION: the corrective move the medicine requires — it MUST instantiate ONE of the partner's numbered canonical acts and keep ITS KIND OF ACTION: if that act is moving, the operation moves; if keeping, it keeps; if releasing, it releases; it may involve speaking, writing or asking ONLY if that canonical act itself is speaking, writing or asking · INVARIANT: the relation that must stay true across any wording.
Return ONLY JSON: {"CONDITION":"…","DOMAIN":"…","OPERATION":"…","OPERATION_SOURCE":<the number of the canonical act it instantiates>,"INVARIANT":"…"}`;
const ask = async (u) => { const { data } = await callProvider({ model: MODEL_IDS.sonnet, max_tokens: 600, system: SYS, messages: [{ role: 'user', content: u }] }, { tag: 'scaffold' }); const raw = data?.content?.map((c) => c.text || '').join('') || ''; try { return JSON.parse(raw.match(/\{[\s\S]*\}/)[0]); } catch { return null; } };
const FSYS = `Classify the PRIMARY ACTION each numbered instruction asks a person to perform into exactly one family: ${FAMILIES.join(', ')}. SAY = speak/tell/name aloud/declare; WRITE = write/list/note; ASK = question someone; OBSERVE = look/notice/trace/examine/sense/reason; CHOOSE = decide/pick/commit; STOP = stop/refuse/drop; KEEP = keep/hold/maintain/defend/persist; RELEASE = let go/end/put down/close; MAKE = build/make/finish/practise/tend; MOVE = go/step/start/act; JOIN = be with/connect/share; SEPARATE = sort/distinguish; PROTECT = guard/boundary; WAIT = pause/rest/leave undecided; CHANGE = adjust/rebalance; FEEL = feel/enjoy/take in. Reply ONLY "<number> <FAMILY>" lines.`;
const famOf = async (texts) => { const { data } = await callProvider({ model: MODEL_IDS.sonnet, max_tokens: 800, system: FSYS, messages: [{ role: 'user', content: texts.map((t, i) => `${i + 1}. ${t}`).join('\n') }] }, { tag: 'scaffold' }); const raw = data?.content?.map((c) => c.text || '').join('\n') || ''; const o = {}; for (const l of raw.split('\n')) { const m = l.match(/^\s*(\d+)[^A-Z]*([A-Z]+)/); if (m && FAMILIES.includes(m[2])) o[Number(m[1])] = m[2]; } return texts.map((_, i) => o[i + 1] || 'OTHER'); };
const derive = async (d) => {
  const s = sources(d); let sc = await ask(s.text); let tries = 1;
  const check = async (x) => { if (!x?.OPERATION) return { ok: false, why: 'no operation' }; const src = s.acts[(Number(x.OPERATION_SOURCE) || 1) - 1] || s.acts[0]; const [fam] = await famOf([x.OPERATION]); const verbalLeak = VERBAL.has(fam) && !VERBAL.has(src?.family); const ok = !verbalLeak && (fam === src?.family || (s.acts.some((a) => a.family === fam) && !VERBAL.has(fam))); return { ok, fam, srcFam: src?.family, srcAct: src?.act, verbalLeak }; };
  let c = await check(sc);
  if (!c.ok) { tries++; const again = await ask(`${s.text}\n\nYOUR LAST OPERATION ("${sc?.OPERATION}") had the kind of action ${c.fam}, but the canonical act it should instantiate ("${c.srcAct}") is ${c.srcFam}. Keep the canonical act's kind of action; speaking, writing or asking only if that act itself is.`); const c2 = await check(again); if (again && (c2.ok || !c.ok)) { sc = again; c = c2; } }
  return { draw: `${STATUS_INFO[d.status].name} ${getComponent(d.transient)?.name} in ${getComponent(d.position)?.name}`, partner: s.partner, sc, ...c, tries, cellAsk: lookupCell(d.transient, d.position, d.status)?.ask || '' };
};
let draws = [];
if (MODE === 'corpusb') { const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } }); const { data } = await db.from('external_readings').select('request_id, draws').like('request_id', 'readability-2026-10-05-B-%').order('created_at', { ascending: true }); draws = data.map((r) => ({ id: r.request_id, d: r.draws[0] })); }
else { let seed = 7; const rnd = (n) => { seed = (seed * 1103515245 + 12345) % 2147483648; return seed % n; }; for (let i = 0; i < NS; i++) draws.push({ id: `sample-${i + 1}`, d: { transient: rnd(78), position: rnd(22), status: 1 + rnd(4) } }); }
const res = []; for (const x of draws) { const r = await derive(x.d); res.push({ id: x.id, ...r }); process.stdout.write(`${x.id.replace('readability-2026-10-05-', '')}: ${r.ok ? 'ok ' : 'LEAK'} ${String(r.fam).padEnd(8)} ← canon ${String(r.srcFam).padEnd(8)} ${r.partner} · tries ${r.tries}\n`); }
const cellFam = await famOf(res.map((r) => r.cellAsk || 'none'));
const vDer = res.filter((r) => VERBAL.has(r.fam)).length, vCell = cellFam.filter((f) => VERBAL.has(f)).length, vCanonSrc = res.filter((r) => VERBAL.has(r.srcFam)).length;
const lines = [`# LAB — the scaffold floor, DERIVED with the operation-family invariant (${MODE}, ${res.length} draws)`, `*True, 2026-10-06, Air's order 1. Never on the floor. Each OPERATION names the canonical act it instantiates and must keep that act's family (lib/pour/actFamilies.json); verbal only where the act is verbal; one retry.*`, '', '| measure | count |', '|---|---|', `| operations keeping their canonical act's family | ${res.filter((r) => r.ok).length} of ${res.length} |`, `| verbal operations (SAY/WRITE/ASK) — derived scaffold | ${vDer} of ${res.length} |`, `| verbal operations — the canonical source acts | ${vCanonSrc} of ${res.length} |`, `| verbal asks — the poured cells for the same draws | ${vCell} of ${res.length} |`, `| retries needed | ${res.filter((r) => r.tries > 1).length} |`, '', '## The scaffolds', ''];
res.forEach((r, i) => lines.push(`### ${r.id.replace('readability-2026-10-05-', '')} · ${r.draw} → ${r.partner}`, `- CONDITION: ${r.sc?.CONDITION}`, `- DOMAIN: ${r.sc?.DOMAIN}`, `- OPERATION: ${r.sc?.OPERATION} — **${r.fam}** (canonical act: "${r.srcAct}", ${r.srcFam})${r.ok ? '' : ' — **FAILED THE INVARIANT**'}`, `- INVARIANT: ${r.sc?.INVARIANT}`, `- the poured cell's ask, for contrast: ${r.cellAsk} — ${cellFam[i]}`, ''));
fs.writeFileSync(`G:/My Drive/For Air Review/LAB_Scaffold_Derived_${MODE}_2026-10-06.md`, lines.join('\n'));
console.log('\n' + lines.slice(3, 10).join('\n'));
