// INSPECT — every Too Little and Too Much status line in the record (78 signatures + 22 positions), with the shapes that hand the Reader a
// biography or a verdict counted: "past experiences", "chronic", "inability/can't/never", clinical labels. Writes the full table to the shelf.
//   npx tsx scripts/inspect_tl_tm_lines.mjs
import fs from 'node:fs';
const DEFS = (await import('../lib/data/nirmanakaya_78_definitions.json', { with: { type: 'json' } })).default;
const { STATUSES, STATUS_INFO } = await import('../lib/constants.js');
const rows = [];
const pick = (states, k) => states?.[k] ?? states?.[k === 'tooLittle' ? 'too_little' : 'too_much'] ?? states?.[k === 'tooLittle' ? 3 : 2] ?? '';
for (const [id, s] of Object.entries(DEFS.signatures || {})) rows.push({ kind: 'signature', id: Number(id), name: s.name, cls: s.class, tl: pick(s.states, 'tooLittle'), tm: pick(s.states, 'tooMuch') });
for (const [id, p] of Object.entries(DEFS.positions || {})) rows.push({ kind: 'position', id: Number(id), name: p.name, cls: 'Position', tl: pick(p.states, 'tooLittle'), tm: pick(p.states, 'tooMuch') });
const SHAPES = { 'past experiences': /\bpast experience/i, 'history clause (have made / has made / learned / once)': /\b(?:have made|has made|learned|once|used to|no longer|years)\b/i, 'chronic': /\bchronic/i, 'inability / can\'t / never / unable': /\b(?:inability|can'?t|cannot|never|unable|incapable)\b/i, 'clinical label': /\b(?:depress|anxi|paralys|disorder|addict|compulsi|dissociat|trauma|numb|burnout|phobi)/i, 'verdict word (failure / collapse / dead / lost)': /\b(?:failure|collapse|dead|lost|ruin|broken)\b/i };
const count = (field) => Object.fromEntries(Object.entries(SHAPES).map(([n, re]) => [n, rows.filter((r) => re.test(r[field] || '')).length]));
const out = [`# INSPECTION — the Too Little and Too Much status lines of the record, every one`, `*True, 2026-10-05. The founder: "we do the Too Little sweep; maybe a Too Much sweep as well." Air: inspect whether the history clause is intended across the full set before any record changes. This is the inspection, written as the draft the founder reads before anything is applied — the same door the Unacknowledged sweep (.659) went through. Source: lib/data/nirmanakaya_78_definitions.json (${rows.filter((r) => r.kind === 'signature').length} signatures, ${rows.filter((r) => r.kind === 'position').length} positions).*`, '', '## What the gaveled definitions say the statuses ARE', '', ...[2, 3].map((i) => `- **${STATUSES[i]?.name}** — ${STATUSES[i]?.desc || ''}${STATUS_INFO?.[i]?.description ? `\n  STATUS_INFO: ${STATUS_INFO[i].description}` : ''}${STATUSES[i]?.extended ? `\n  extended: ${STATUSES[i].extended}` : ''}`), '', '## The shapes, counted across all 100 lines', '', '| shape | Too Little lines | Too Much lines |', '|---|---|---|', ...Object.keys(SHAPES).map((n) => `| ${n} | ${count('tl')[n]} | ${count('tm')[n]} |`), '', `Too Little lines that carry NONE of the shapes: ${rows.filter((r) => !Object.values(SHAPES).some((re) => re.test(r.tl || ''))).length} of ${rows.length} · Too Much lines with none: ${rows.filter((r) => !Object.values(SHAPES).some((re) => re.test(r.tm || ''))).length} of ${rows.length}`, '', '## Every line', '', '| id | name | class | TOO LITTLE | TOO MUCH |', '|---|---|---|---|---|', ...rows.map((r) => `| ${r.id} | ${r.name} | ${r.cls} | ${String(r.tl).replace(/\|/g, '/')} | ${String(r.tm).replace(/\|/g, '/')} |`)];
const path = 'G:/My Drive/For Air Review/INSPECTION_True_Too_Little_And_Too_Much_Record_Lines_2026-10-05.md'; fs.writeFileSync(path, out.join('\n'));
console.log(out.slice(0, 20).join('\n')); console.log('\nshelf:', path);
// distinct Too Little texts (the sweep's unit)
const tlDistinct = new Map(); for (const r of rows) tlDistinct.set(r.tl, (tlDistinct.get(r.tl) || 0) + 1);
console.log(`\ndistinct Too Little texts: ${tlDistinct.size} · distinct Too Much texts: ${new Set(rows.map((r) => r.tm)).size}`);
console.log('most repeated TL texts:'); for (const [t, n] of [...tlDistinct.entries()].sort((a, b) => b[1] - a[1]).slice(0, 6)) console.log(`  ×${n}  ${t}`);
