// .697: merge the 78 medicine operations + the 4 mechanism lines into lib/data/plain_propositions.json, with the canonical beside each; check them
import fs from 'node:fs';
const { getComponent } = await import('../lib/corrections.js');
const P = JSON.parse(fs.readFileSync('lib/data/plain_propositions.json', 'utf8')); const M = JSON.parse(fs.readFileSync('scripts/medicine_operations_2026-10-05.json', 'utf8'));
P.medicine = {}; for (let id = 0; id < 78; id++) { const c = getComponent(id) || {}; if (!M.medicine[String(id)]) throw new Error('missing ' + id); P.medicine[String(id)] = { name: c.name, canonical: c.description || '', operation: M.medicine[String(id)] }; }
P.mechanism = { '1': { canonical: 'GROWTH (Balanced): an invitation, optional by definition; what this balance is free to feed next.', plain: M.mechanism['1'] }, '2': { canonical: "DIAGONAL (Too Much): the capacity in excess crosses the map to the opposite element; the medicine is the partner's own action.", plain: M.mechanism['2'] }, '3': { canonical: "VERTICAL (Too Little): the seat is running on empty; the medicine is to charge its vertical twin — energy into the partner's own action pulls the current through the starved seat. Never push effort or feeling into the empty seat directly.", plain: M.mechanism['3'] }, '4': { canonical: 'REDUCTION (Unacknowledged): authorship misattributed; the medicine returns toward the simpler, earlier form of the same line.', plain: M.mechanism['4'] } };
P._meta.shipped = "0.99.697 — + the medicine block: the way through as an OPERATION (78, by hand) + the mechanism (4) + the medicine's face (= the parent's Balanced line). Air's rule rides in the Handing: instantiate inside the person's own problem; add a circumstance only when their words carry it or the act needs it.";
const house = /\b(seat|signature|archetype|authorship|transient|durable|Gestalt|portal|rebalanc|medicine|Wheel|Fruition|Seed|Bridge|Feedback|agency|channel)\b/i; const leaks = []; const som = [];
for (const [id, m] of Object.entries(P.medicine)) { if (house.test(m.operation)) leaks.push(id + ': ' + m.operation.match(house)[0]); if (/\bsome ?thing\b/i.test(m.operation)) som.push(id); }
fs.writeFileSync('lib/data/plain_propositions.json', JSON.stringify(P, null, 2) + '\n');
const w = Object.values(P.medicine).map((m) => m.operation.split(/\s+/).length);
console.log('medicine 78 merged · house words:', leaks.length ? leaks.join(' · ') : 'none', '· free something:', som.length ? som.join(',') : 'none', '· words min/max/mean', Math.min(...w), Math.max(...w), (w.reduce((a, b) => a + b, 0) / 78).toFixed(1));
